(function(g){var window=this;var x1=function(a){var b={format:a.o,languageCode:a.l,languageName:a.A,displayName:g.wv(a),kind:a.B,name:a.C,id:a.Ea,is_servable:a.O,is_default:a.isDefault,is_translateable:a.G,vss_id:a.D};a.g&&(a=a.g,b.translationLanguage={languageCode:a.languageCode,languageName:a.languageName,languageOriginal:a.g,id:a.id,is_default:a.isDefault});return b},y1=function(a){return a.g?a.g.languageCode:a.l},Xja=function(a,b){var c=new g.vv;
c.l=a.l;c.A=a.A;c.C=a.C;c.B=a.B;c.isDefault=!1;c.G=a.G;c.D=a.D;c.I=a.I;c.g=b;return c},z1=function(a){if(!Yja.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(Zja,"#$1$1$2$2$3$3"));a=a.toLowerCase();return[(0,window.parseInt)(a.substr(1,2),16),(0,window.parseInt)(a.substr(3,2),16),(0,window.parseInt)(a.substr(5,2),16)]},A1=function(a,b,c,d,e,f,k){f=void 0===f?!1:f;
k=void 0===k?null:k;g.VD.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.o=f;this.l=k},B1=function(a,b,c,d,e){g.VD.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.l=[]},D1=function(a){a=void 0===a?{}:a;
var b="_"+C1++;return new B1(0,0x8000000000000,0,b,a)},F1=function(a,b,c,d,e,f){var k={};
g.Ma(k,b);g.Ma(k,a.params);g.Ma(k,c);var l={};g.Ma(l,b.Ma);a.params.Ma&&g.Ma(l,a.params.Ma);g.Ma(l,c.Ma);k.Ma=l;g.R.call(this,{F:"div",H:"caption-window",N:{id:"caption-window-"+a.id,dir:1==k.gi?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:k.lang},K:[{F:"span",H:"captions-text"}]});this.A=[];this.M=!1;this.D=a;this.C=[];this.G=[];this.Fa=e;this.Ba=f;this.B=null;this.Y=.96*e;this.la=.96*f;this.l=k;this.va=c;this.o=this.g["captions-text"];this.na=null!=this.o.style["box-decoration-break"]||
null!=this.o.style["-webkit-box-decoration-break"];this.O=d/360*16;this.type=0;this.ga=this.O*E1(l);a=new g.rt(this.element,!0);g.I(this,a);a.subscribe("dragstart",this.WE,this);a.subscribe("dragmove",this.VE,this);a.subscribe("dragend",this.UE,this);this.ea=this.ca=0;a="";this.l.windowOpacity&&(a=z1(this.l.windowColor),a="rgba("+a[0]+","+a[1]+","+a[2]+","+this.l.windowOpacity+")");b={"background-color":a,display:!1===this.l.isVisible?"none":"","text-align":$ja[this.l.textAlign]};this.na&&(b["border-radius"]=
a?this.ga/8+"px":"");g.Kh(this.element,b);switch(this.l.ne){case 0:case 1:case 2:g.J(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.J(this.element,"ytp-caption-window-bottom")}},E1=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0==a.offset||2==a.offset)b*=.8;return b},G1=function(a,b){var c={},d=b.background?b.background:a.l.Ma.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.l.Ma.backgroundOpacity;d=z1(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.na&&(c["box-decoration-break"]="clone",c["border-radius"]=a.ga/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.O*E1(b)+"px";d=1;e=b.color||a.l.Ma.color;if(b.color||null!=b.textOpacity)e=z1(e),d=null==b.textOpacity?a.l.Ma.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",c.color=
e,c.fill=e;var f=b.charEdgeStyle;0==f&&(f=null);if(f){e="rgba(34, 34, 34, "+d+")";var k="rgba(204, 204, 204, "+d+")";b.Kr&&(k=e=b.Kr);var l=a.O/16/2,m=Math.max(l,1),n=Math.max(2*l,1),q=Math.max(3*l,1),u=Math.max(5*l,1);d=[];switch(f){case 4:for(;q<=u;q+=l)d.push(n+"px "+n+"px "+q+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=q;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+k);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(q=0;5>q;q++)d.push("0 0 "+n+"px "+
e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.js()?'"Carrois Gothic SC", sans-serif-smallcaps':
'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.l.Ma.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7==b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.Wd&&(c["font-style"]="italic");b.underline&&(c["text-decoration"]="underline");
b.bo&&(c.visibility="hidden");return c},H1=function(a,b,c){a.M=a.M||!!c;
var d={};g.Ma(d,a.l.Ma);g.Ma(d,c||b.l);g.Ma(d,a.va.Ma);c=a.C[0];if(c&&d.background==c.background&&d.backgroundOpacity==c.backgroundOpacity&&!!d.bo==!!c.bo&&d.charEdgeStyle==c.charEdgeStyle){var e;for(e=0;e<a.C.length;e++)if(g.pc(d,a.C[e])){var f=a.G[e];break}if(!f){e={};for(var k in d)d[k]!=c[k]&&(e[k]=d[k]);f=g.Zd("SPAN");g.Kh(f,G1(a,e));a.G[0].appendChild(f);e=1}a.G.length=e;a.C.length=e}else a.G.length=0,a.C.length=0,f=g.Zd("SPAN"),g.Kh(f,G1(a,d)),a.o.appendChild(f);a.B&&a.B.parentNode!=f&&(g.de(a.B),
f.appendChild(a.B));c=(k=g.v(b.text))?b.text.split("\n"):[b.text];for(e=0;e<c.length;e++){var l=c[e];if(0<e||0==a.A.length||!b.o){if(0<e||0!=a.A.length){var m=g.Zd("BR");f.appendChild(m)}f.appendChild(g.$d("\u00a0"));a.B=g.$d("\u00a0");f.appendChild(a.B)}l&&(m=a.B,m.parentNode&&m.parentNode.insertBefore(k?g.$d(l):l,m))}a.C.push(d);a.G.push(f);a.A.push(b)},I1=function(){},K1=function(){this.A=this.l=this.mode=this.o=0;
this.B=new J1(this);this.C=new J1(this);this.g=[];this.clear()},aka=function(a,b,c){if(255==a&&255==b||!a&&!b)return{ck:a,
dk:b,result:0};a=L1[a];b=L1[b];if(a&128){if(!(b&128)&&0!=c.g&&c.l==b)return{ck:a,dk:b,result:1}}else if(b&128&&1<=a&&31>=a)return{ck:a,dk:b,result:2};return{ck:a,dk:b,result:3}},bka=function(a,b,c,d){255==b&&255==c||!b&&!c?(45==++a.A&&a.reset(),a.B.g.clear(),a.C.g.clear()):(a.A=0,M1(a.B,b,c,d))},cka=function(a,b){a.g.sort(function(a,b){var c=a.time-b.time;
return 0==c?a.order-b.order:c});
for(var c=0;c<a.g.length;c++){var d=a.g[c];a.l=d.time;0==d.type?bka(a,d.Er,d.Gr,b):1==d.type&&a.o&496&&M1(a.C,d.Er,d.Gr,b)}a.g.length=0},N1=function(){this.g=0},O1=function(){this.l=this.o=this.g=0},P1=function(){this.timestamp=this.xd=0},Q1=function(a){this.o=[];
for(var b=0;15>=b;b++){this.o[b]=[];for(var c=0;32>=c;c++)this.o[b][c]=new P1}this.g=this.l=this.row=0;this.style=new N1;this.B=a;this.A=0},R1=function(a,b){if(3==a.style.g){for(var c=0,d=0,e=a.B.l+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,q=d?d:1;32>=q;++q){var u=a.o[m][q];
if(0!=u.xd){0==c&&(c=m,d=q);n=String.fromCharCode(u.xd);var w=u.timestamp;w<e&&(e=w);u.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0==u.xd||32==q)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.B(c,d,e,l,f)}else for(d=c=0,f=e=a.B.l+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(q=a.o[k][m],u=q.xd,0!=u&&(0==c&&(c=k,d=m),n=String.fromCharCode(u),w=q.timestamp,w<=e&&(e=w),l+=n,q.reset()),32==m||0==u)l&&b.B(c,d,e,f,l),e=f,l="",d=c=0},hka=function(a,b){switch(a){case 0:return dka[(b&127)-32];
case 1:return eka[b&15];case 2:return fka[b&31];case 3:return gka[b&31]}return 0},S1=function(a){return a.o[a.row][a.l]},T1=function(a,b,c){2<=b&&1<a.l&&(--a.l,S1(a).xd=0);
var d=S1(a);d.timestamp=a.B.l+0;d.xd=hka(b,c);32>a.l&&a.l++},U1=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++)a.o[b+e][f].qk(a.o[c+e][f])},V1=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.o[b+d][e].reset()},W1=function(a){a.row=0<a.g?a.g:1;
a.l=1;V1(a,0,15)},X1=function(a){this.A=a;
this.B=0;this.style=new N1;this.C=new Q1(a);this.D=new Q1(a);this.G=new Q1(a);this.l=this.C;this.o=this.D;this.g=this.l},Y1=function(a,b,c){var d=a.l,e=!1;
switch(a.style.get()){case 4:if(0<d.g)break;case 1:case 2:R1(d,c),W1(a.l),W1(a.o),d.row=15,d.g=b,e=!0}a.style.set(3);a.g=d;a.g.style=a.style;a.A.mode=1<<d.A;e?d.l=1:d.g!=b&&(d.g>b?(R1(d,c),V1(d,d.row-d.g,b)):d.row<b&&(b=d.g),d.g=b)},Z1=function(a){a.style.set(1);
a.g=a.o;a.g.g=0;a.g.style=a.style;a.A.mode=1<<a.g.A},$1=function(a){a.style.set(4);
a.g=a.G;a.g.style=a.style;a.A.mode=1<<a.g.A},J1=function(a){this.l=a;
this.g=new O1;this.B=0;this.o=new X1(a);this.C=new X1(a);this.A=this.o},M1=function(a,b,c,d){a.g.update();
b=aka(b,c,a.g);switch(b.result){case 0:return;case 1:case 2:return}var e=b.ck;c=b.dk;if(32<=e||!e)a.l.mode&a.l.o&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.A.g,b&96&&T1(a,0,b),c&96&&T1(a,0,c),0!=b&&0!=c&&3==a.style.g&&R1(a,d));else if(e&16)a:if(!a.g.matches(e,c)&&(b=a.g,b.o=e,b.l=c,b.g=2,b=e&8?a.C:a.o,a.A=b,a.l.mode=1<<(a.B<<2)+(b.B<<1)+(4==b.style.g?1:0),(a.l.mode|1<<(a.B<<2)+(b.B<<1)+(4!=b.style.g?1:0))&a.l.o))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];a=c&16?4*((c&14)>>1):
0;c=b.g;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!=c.row){if(d<c.g&&(d=c.g,d==c.row))break;var f=1+c.row-c.g,k=1+d-c.g;U1(c,k,f,c.g);b=f;e=c.g;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));V1(c,b,e)}}c.row=d;c.l=a+1}else switch(e&7){case 1:switch(c&112){case 32:T1(b.g,0,32);break a;case 48:57==c?(b=b.g,S1(b).xd=0,32>b.l&&b.l++):T1(b.g,1,c&15)}break;case 2:c&32&&T1(b.g,2,c&31);break;case 3:c&32&&T1(b.g,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:Z1(b);break;case 33:b=
b.g;1<b.l&&(--b.l,S1(b).xd=0);break;case 36:b=b.g;d=S1(b);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(b.o[a][c]==d){for(;32>=c;c++)b.o[a][c].reset();break}break;case 37:Y1(b,2,d);break;case 38:Y1(b,3,d);break;case 39:Y1(b,4,d);break;case 40:T1(b.g,0,32);break;case 41:b.style.set(2);b.g=b.l;b.g.g=0;b.g.style=b.style;b.A.mode=1<<b.g.A;break;case 42:d=b.G;d.g=15;d.style.set(4);W1(d);$1(b);break;case 43:$1(b);break;case 44:a=b.l;switch(b.style.get()){case 1:case 2:case 3:R1(a,d)}V1(a,0,15);break;case 45:b:{a=
b.g;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.l=1;break b}case 3:}2>a.g&&(a.g=2,a.row<a.g&&(a.row=a.g));b=a.row-a.g+1;R1(a,d);U1(a,b,b+1,a.g-1);V1(a,a.row,1)}break;case 46:V1(b.o,0,15);break;case 47:R1(b.l,d);d=b.o;a=b.A.l+0;for(c=1;15>=c;++c)for(e=1;32>=e;++e)d.o[c][e].timestamp=a;d=b.o;b.o=b.l;b.l=d;Z1(b)}break;case 7:switch(c){case 33:case 34:case 35:b=b.g,32<(b.l+=c&3)&&(b.l=32)}}},a2=function(){},b2=function(a){this.l=a;
this.g=null},d2=function(a,b,c){var d=a.getAttribute("t");
d=d?(0,window.parseInt)(d,10):1E3*(0,window.parseFloat)(a.getAttribute("start")||0);var e=a.getAttribute("d");e=e?(0,window.parseFloat)(e):1E3*(0,window.parseFloat)(a.getAttribute("dur")||0);b=a.getAttribute("w")||b;var f=!!a.getAttribute("append"),k=f?6:5;a=g.nq("<html>"+(a.firstChild&&a.firstChild.nodeValue||"")+"</html>");c2(d,e,k,b,f,a.firstChild,{},c)},c2=function(a,b,c,d,e,f,k,l){switch(f.tagName){case "b":k.bold=!0;
break;case "i":k.Wd=!0;break;case "u":k.underline=!0;break;case "font":var m=f.getAttribute("color");e2.test(m);k.color=m}for(m=0;m<f.childNodes.length;m++){var n=f.childNodes[m];if(3==n.nodeType)l.push(new A1(a,b,c,d,n.nodeValue,e||0<m,g.lc(k)?void 0:k));else{var q={};g.Ma(q,k);c2(a,b,c,d,e||0<m,n,q,l)}}},f2=function(){this.l={};
this.g=null},g2=function(a){this.A={};
this.I={};this.J={};this.B="_"+C1++;this.C=a;this.G={};this.l=this.g=null;this.D=!0},h2=function(a,b){var c=a.getAttribute(b);
if(null!=c)return(0,window.parseFloat)(c)},i2=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"==c},j2=function(a,b){var c=h2(a,b);
if(void 0!=c)return c},k2=function(a,b){var c=a.getAttribute(b);
if(null!=c)return e2.test(c),c},l2=function(a,b){var c={},d=b.getAttribute("ws");
g.Ma(c,d?a.J[d]:a.C);d=j2(b,"mh");null!=d&&(c.Do=d);d=j2(b,"ju");null!=d&&(c.textAlign=d);d=j2(b,"pd");null!=d&&(c.gi=d);d=k2(b,"wfc");null!=d&&(c.windowColor=d);d=h2(b,"wfo");void 0!=d&&(c.windowOpacity=d/255);return c},m2=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Ma(c,a.I[d]);d=j2(b,"ap");null!=d&&(c.ne=d);d=h2(b,"cc");null!=d&&(c.hn=d);d=h2(b,"ah");null!=d&&(c.Id=d);d=h2(b,"rc");null!=d&&(c.jm=d);d=h2(b,"av");null!=d&&(c.He=d);return c},n2=function(a,b,c,d){var e={};
g.Ma(e,m2(a,b));g.Ma(e,l2(a,b));d?g.pc(e,a.C)?(d=a.B,e=a.C):d="_"+C1++:d=b.getAttribute("id")||"_"+C1++;a=h2(b,"t")+c;b=h2(b,"d")||0x8000000000000;return new B1(a,b,0,d,e)},o2=function(a,b,c){this.D=c;
this.version=this.C=this.A=this.g=0;this.l=new window.DataView(a);this.o=[]},p2=function(a){var b=a.g;
a.g+=1;return a.l.getUint8(b)},q2=function(a){var b=a.g;
a.g+=4;return a.l.getUint32(b)},r2=function(a,b){this.l=a;
this.track="CC3"==b.A?4:0;this.g=new K1;this.g.o=1<<this.track},t2=function(a){if(g.v(a))return!1;
a=new o2(a,8,0);return s2(a)},s2=function(a){if(!(a.g<a.l.byteLength)||1380139777!=q2(a))return!1;
a.version=p2(a);if(1<a.version)return!1;p2(a);p2(a);p2(a);return!0},ika=function(){this.l=[];
this.g=[]},u2=function(a,b){return b?a.g.concat(a.l):a.g},v2=function(a,b){switch(b.B){case "asr":var c=a.l;
g.Ra(c,(0,g.A)(b.J,b))||c.push(b);break;default:c=a.g,g.Ra(c,(0,g.A)(b.J,b))||c.push(b)}},w2=function(){},x2=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.Wd=!0;break;case "u":l.underline=!0}for(var n=0;n<k.childNodes.length;n++){var q=k.childNodes[n];if(3==q.nodeType)q=new A1(b,c,d,e.id,q.nodeValue,f||0<n,g.lc(l)?void 0:l),m.push(q),e.l.push(q);else{var u={};g.Ma(u,l);x2(a,b,c,d,e,!0,q,u,m)}}},y2=function(a){var b=0;
a=g.p(a.split(":"));for(var c=a.next();!c.done;c=a.next())b=60*b+(0,window.parseFloat)(c.value);return 1E3*b},z2=function(a,b,c,d){d=Object.assign({Do:0},d);
return new B1(a,b,c,"_"+C1++,d)},A2=function(a){g.G.call(this);
this.Dt=!!a;this.l=new ika;this.D=[];this.g=null},B2=function(a){var b={};
if(a=y1(a))b.lang=a,jka.test(a)&&(b.gi=1);return b},kka=function(a,b,c,d,e){d=d||0;
e=e||0;if(!g.v(b)){var f=new window.DataView(b);if(1718909296==f.getUint32(4)&&(f=g.jx(f,1835295092),b=b.slice(f.dataOffset,f.dataOffset+f.size),!t2(b)&&(b=g.xe(new window.Uint8Array(b)),!b)))return[]}if(g.v(b)){if("WEBVTT"==b.substring(0,6))return a.g||(a.g=new w2),a.g.o(b,d);b=g.nq(b);if(!b||!b.firstChild)return[];if(!a.g)if("timedtext"==b.firstChild.tagName)3==(0,window.parseInt)(b.firstChild.getAttribute("format"),10)?a.g=new g2(B2(c)):a.g=new f2;else try{return a.g=new b2(B2(c)),a.g.o(b,d)}catch(k){return g.N(k),
a.g=null,[]}return a.g.o(b,d)}try{if(t2(b))return a.g||(a.g=new r2(e,c)),a.g.o(b,d)}catch(k){g.N(k),a.g=null}return[]},C2=function(a){A2.call(this,a.jk);
this.A=void 0;this.o=null;this.D=a.captionTranslationLanguages},D2=function(){this.Sa=[]},E2=function(a,b,c,d,e,f){g.G.call(this);
this.M=a;this.A=b;this.C=new D2;this.g=null;this.I=d;this.O=f;this.o=this.l=null;this.G=c;this.D=e||!1;this.J=new g.L(this.Yt,1E3,this);g.I(this,this.J);this.B=new g.nt(this);g.I(this,this.B);this.B.L(b,"seekto",this.Wu);this.Wu(b.getCurrentTime());this.Yt()},F2=function(a,b){var c=a.g;
a.g=g.Oa(a.G.Xe(b).g);c!=a.g&&a.O&&a.O()},G2=function(a,b){var c=g.Ey(b,a.M,{}).vb(),d={format:"RAW",
withCredentials:!0};a.D&&(d.responseType="arraybuffer");a.o=g.ws(c,d,3,100).then((0,g.A)(a.yJ,a));a.l=b;c=a.C;d=a.l.g[0].oa;var e=g.lb(c.Sa,d);0<=e||0>e&&1==(-e-1)%2||(e=-e-1,0<e&&1==d-c.Sa[e-1]&&e<c.Sa.length&&1==c.Sa[e]-d?(g.Ya(c.Sa,e),g.Ya(c.Sa,e-1)):0<e&&1==d-c.Sa[e-1]?c.Sa[e-1]=d:e<c.Sa.length&&1==c.Sa[e]-d?c.Sa[e]=d:(g.gb(c.Sa,e,0,d),g.gb(c.Sa,e+1,0,d)))},H2=function(a,b){A2.call(this);
this.o=a;this.A=b;this.B=null;this.C=!1},lka=function(a,b){if(b in a.o.g)return a.o.g[b];
if(g.fz(a.o))for(var c in a.o.g){var d=a.o.g[c];if(g.Nv(d.info.mimeType)&&("386"!=c||!g.S(g.V(a.A).experiments,"html5_manifestless_captions_fmt3_killswitch")))return d}return null},I2=function(a,b){return a.ra&&null!=a.ka||g.V(b).Ha&&null!=a.ka&&null!=a.ka.g.rawcc},J2=function(a,b,c,d,e,f){F1.call(this,a,b,c,d,e,f);
this.type=1},K2=function(a,b,c,d,e,f){F1.call(this,a,b,c,d,e,f);
g.J(this.element,"ytp-caption-window-rollup");this.type=2;this.J=this.R=0;this.T=this.I=window.NaN;this.pa=null;this.X=new g.L(this.DJ,433,this);g.I(this,this.X)},L2=function(a){if(!a.R){var b=g.Zd("SPAN");
g.Kh(b,G1(a,a.l.Ma));a.o.appendChild(b);b.appendChild(g.$d("M"));var c=b.offsetHeight,d=g.Zd("BR");b.appendChild(d);b.appendChild(g.$d("M"));a.R=b.offsetHeight-c;a.o.removeChild(b)}return a.R},mka=function(a){if((0,window.isNaN)(a.I)){var b=a.l.hn;
if(b){var c=g.Zd("SPAN");g.me(c,"\u2013".repeat(b));g.Kh(c,G1(a,a.l.Ma));a.o.appendChild(c);a.I=c.offsetWidth;a.o.removeChild(c)}else a.I=0}return a.I},M2=function(a,b,c,d){A2.call(this,d);
c=c||g.Qr(a).hl||"";c=c.split("_").join("-");this.B=g.Sr(a,{hl:c});this.A=b;this.C={};this.o=null},P2=function(a){g.zK.call(this,a);
this.A=g.V(a);this.o=a.getVideoData();this.na=g.QJ(a);this.J=a;var b=null,c=g.cr("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.Nq(c));this.X=b;this.C={Ma:{}};this.G={Ma:{}};this.R=[];this.T={};this.Y={};this.O=!1;this.pa="1"==this.o.Hb.cc_auto_caps||"1"==this.A.Ob.cc_auto_caps;b="3"==this.A.A&&!!a.app.B&&a.app.B.Hj();this.D=(c=!g.S(this.A.experiments,"web_player_native_controls_live_captions_fix_killswitch"))?b&&!this.o.ra:b;this.ea=c&&b&&this.o.ra&&I2(this.o,this.J);c=b=this.l=this.B=
this.I=this.M=this.Z=this.la=null;this.D||(b=new g.rq(this.Ay,void 0,this),g.I(this,b),c=new g.L(this.ZK,2E3,this),g.I(this,c));this.fa=b;this.ca=c;this.ba=new g.nt(this);g.I(this,this.ba);this.D||this.ba.L(a,"resize",this.uq);this.ba.L(a,"onPlaybackAudioChange",this.ZG);this.ba.L(a,"crn_captions",this.cD,this);this.ba.L(a,"crx_captions",this.dD,this);N2(this,O2(this,"display-settings")||{})},Q2=function(a){if(1==a.A.Df||1==a.o.Df||"alwayson"==g.tC(a.o,"yt:cc"))return!0;
if(2==a.A.Df){var b=O2(a,"module-enabled");if(null!=b)return!!b}if(a.o.captionTracks.length)var c=a.g.getAudioTrack().cn;return"ON"==c||"on"==g.tC(a.o,"yt:cc")},R2=function(a,b){if(a.l&&(void 0===b||!b)||!a.o.captionTracks.length)return!1;
var c=a.g.getAudioTrack();return!!c.Ek||"FORCED_ON"==c.cn},T2=function(a,b){if(a.B){var c=u2(a.B.l,b||a.pa);
if(a.I&&a.I.g)return a.I.g;for(var d=[a.o.Cf,a.A.Cf,g.tC(a.o,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(y1(c[f])==d[e])return c[f];return a.I&&a.I.qn?a.I.qn:(d=c.find(function(a){return a.isDefault}))?d:c[0]||S2(a)}return null},S2=function(a){return a.I&&a.I.Ek},U2=function(a,b){for(var c=a.J.app.B.ia().textTracks,d=a.l.toString(),e=0;e<c.length;e++){var f=c[e];
f.id==d&&(b?"showing"!=f.mode&&(f.mode="showing"):"showing"==f.mode&&(f.mode="disabled"))}},W2=function(a,b,c,d){a.loaded&&a.unload();
null!=c&&(a.O=c,a.O&&V2(a,"module-enabled",!!b));a.l=b;R2(a)&&(a.l=S2(a));a.load(d)},nka=function(a){if(a.l!=S2(a)){if(a.O&&!g.kA(a.A)&&!g.qA(a.A)){g.wq(a.ca);
var b=D1({ne:0,Id:5,He:5,jm:2,textAlign:0,gi:0,lang:"en"});a.Z=[b];var c=["Click "," for settings"];if(!a.la){var d=new g.Yu(g.BO());g.I(a,d);a.la=d.element}d=b.end-b.start;var e=g.wv(a.l);e&&a.Z.push(new A1(b.start,d,0,b.id,e));a.Z.push(new A1(b.start,d,0,b.id,c[0]),new A1(b.start,d,0,b.id,a.la,!0),new A1(b.start,d,0,b.id,c[1],!0));g.eK(a.g,a.Z);g.uq(a.ca)}if(a.O||g.kA(a.A))V2(a,"module-enabled",!0),a.I&&(a.I.g=a.l);(a=g.W(a.g.app))&&a.C&&g.MC(a.C.o)}},oka=function(a,b){var c=g.qM(a.na,!0).height;
if(!c)return null;var d=a.na.Da();switch(null!=b.params.Do?b.params.Do:b.params.yL?2:1<b.l.length?1:0){case 1:return new J2(b,a.C,a.G,c,d.width,d.height);case 2:return new K2(b,a.C,a.G,c,d.width,d.height);default:return new F1(b,a.C,a.G,c,d.width,d.height)}},N2=function(a,b,c){var d=X2.Ma;
a.C={};g.Ma(a.C,X2);a.C.Ma={};g.Ma(a.C.Ma,d);a.G={Ma:{}};var e=b.backgroundOverride?a.G:a.C,f=b.background||d.background;e2.test(f);e.Ma.background=f;e=b.colorOverride?a.G:a.C;f=b.color||d.color;e2.test(f);e.Ma.color=f;e=b.windowColorOverride?a.G:a.C;f=b.windowColor||X2.windowColor;e2.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.G:a.C;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.Ma.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.G:a.C;f=b.fontSizeIncrement;null==f&&(f=d.fontSizeIncrement);
e.Ma.fontSizeIncrement=f;f=b.fontStyleOverride?a.G:a.C;e=b.fontStyle;null==e&&(e=d.bold&&d.Wd?3:d.bold?1:d.Wd?2:0);f=f.Ma;switch(e){case 1:f.bold=!0;delete f.Wd;break;case 2:delete f.bold;f.Wd=!0;break;case 3:f.bold=!0;f.Wd=!0;break;default:delete f.bold,delete f.Wd}e=b.textOpacityOverride?a.G:a.C;f=b.textOpacity;null==f&&(f=d.textOpacity);e.Ma.textOpacity=f;e=b.windowOpacityOverride?a.G:a.C;f=b.windowOpacity;null==f&&(f=X2.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?a.G:a.C;f=b.charEdgeStyle;
null==f&&(f=d.charEdgeStyle);e.Ma.charEdgeStyle=f;e=b.fontFamilyOverride?a.G:a.C;f=b.fontFamily;null==f&&(f=d.fontFamily);e.Ma.fontFamily=f;a.loaded&&a.uq();c&&V2(a,"display-settings",b)},Z2=function(a,b){if(b&&!a.M){var c=D1({gi:0,
lang:"en"});a.M=[c,new A1(c.start,c.end-c.start,0,c.id,"Captions look like this")];g.eK(a.g,a.M)}else!b&&a.M&&(Y2(a,a.M),a.M=null)},Y2=function(a,b){g.gK(a.g,b);
(0,g.C)(b,function(a){g.Za(this.R,a)},a);
a.fa.Pi()},pka=function(a,b){return a&&g.v(a)&&e2.test(a)?a:b},qka=function(a,b){return g.va(a)&&!(0,window.isNaN)(a)?Math.max(0,Math.min(1,(0,window.parseFloat)(a))):b},rka=function(a,b){return g.va(a)&&!(0,window.isNaN)(a)?g.ud(a,-2,4):b},O2=function(a,b){if(!a.X)return null;
try{var c=a.X.get(b)}catch(d){a.X.remove(b)}return c},V2=function(a,b,c){if(a.X)try{a.X.set(b,c)}catch(d){}};
g.LQ.prototype.lh=g.ca(10,function(){for(var a=g.Id(window.document,"track",void 0,this.g),b=0;b<a.length;b++)g.de(a[b])});
g.LU.prototype.lh=g.ca(9,function(){this.g.lh()});
g.LQ.prototype.Hj=g.ca(8,function(){return!!this.g.textTracks});
g.LU.prototype.Hj=g.ca(7,function(){return this.g.Hj()});
g.LQ.prototype.pi=g.ca(6,function(a){for(var b=0;b<a.length;b++)this.g.appendChild(a[b])});
g.LU.prototype.pi=g.ca(5,function(a){this.g.pi(a)});
g.Qw.prototype.Mk=g.ca(3,function(a){return(a=this.If(a))?a.l:0});
g.Wy.prototype.Mk=g.ca(2,function(){return 0});
g.vv.prototype.J=g.ca(1,function(a){return a?this.toString()==a.toString():!1});
var jka=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Arab|Hebr|Thaa|Nkoo|Tfng))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,Zja=/#(.)(.)(.)/,Yja=/^#(?:[0-9a-f]{3}){1,2}$/i,e2=/^#(?:[0-9a-f]{3}){1,2}$/i;var $ja=["left","right","center"];var X2={windowColor:"#080808",windowOpacity:0,textAlign:2,ne:7,Id:50,He:100,Ma:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.r(A1,g.VD);g.r(B1,g.VD);var C1=0;g.r(F1,g.R);g.h=F1.prototype;g.h.WE=function(a,b){var c=g.di(this.element,this.element.parentElement);this.ca=a-c.x;this.ea=b-c.y;g.J(this.element,"ytp-dragging")};
g.h.VE=function(a,b){var c=g.hi(this.element),d=a-this.ca-.02*this.Fa,e=b-this.ea-.02*this.Ba,f=(d+c.width/2)/this.Y*3;f=Math.floor(g.ud(f,0,2));var k=(e+c.height/2)/this.la*3;k=Math.floor(g.ud(k,0,2));var l=f+3*k;d=(d+f/2*c.width)/this.Y;d=100*g.ud(d,0,1);c=(e+k/2*c.height)/this.la;c=100*g.ud(c,0,1);this.D.params.ne=l;this.D.params.He=c;this.D.params.Id=d;this.l.ne=l;this.l.He=c;this.l.Id=d;this.vx()};
g.h.UE=function(){g.kq(this.element,"ytp-dragging")};
g.h.vx=function(){this.Ug(this.A)};
g.h.Ug=function(a){var b=Math.min(this.Ls(),this.Y),c=this.Ks();g.Kh(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.Um(a);a={transform:"",top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var d=.96*this.l.Id+2,e=this.l.ne;switch(e){case 0:case 3:case 6:a.left=d+"%";break;case 1:case 4:case 7:a.left=d+"%";d=this.o.offsetWidth;b||d?(b=b||d+1,a.width=b+"px",a["margin-left"]=
b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-d+"%"}b=.96*this.l.He+2;switch(e){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.Kh(this.element,a)};
g.h.Um=function(a){var b;for(b=0;b<a.length&&a[b]==this.A[b];b++);if(this.M||this.A.length>b)b=0,this.M=!1,this.A=[],this.C=[],this.G=[],this.B=null,g.be(this.o);for(;b<a.length;b++)H1(this,a[b])};
g.h.Ls=function(){return 0};
g.h.Ks=function(){return 0};I1.prototype.B=function(){};K1.prototype.clear=function(){this.A=this.l=this.mode=0;this.g=[];this.reset()};
K1.prototype.reset=function(){this.mode=0;this.B.reset(0);this.C.reset(1)};
var L1=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];N1.prototype.set=function(a){this.g=a};
N1.prototype.get=function(){return this.g};
O1.prototype.clear=function(){this.g=0};
O1.prototype.update=function(){this.g=2==this.g?1:0};
O1.prototype.matches=function(a,b){return 0!=this.g&&a==this.o&&b==this.l};
P1.prototype.qk=function(a){this.xd=a.xd;this.timestamp=a.timestamp};
P1.prototype.reset=function(){this.timestamp=this.xd=0};
Q1.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.o[b][c];a=0==d.xd?a+"_":a+String.fromCharCode(d.xd)}a+="\n"}return a};
Q1.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.o[b][c].reset();this.A=a;this.g=0;this.l=this.row=1};
var dka=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],eka=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],fka=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],gka=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];X1.prototype.reset=function(a,b){this.B=b;this.style.set(2);this.l=this.C;this.o=this.D;this.g=this.l;var c=(a<<2)+(b<<1);this.C.reset(c);this.D.reset(c);this.G.reset((a<<2)+(b<<1)+1)};
J1.prototype.reset=function(a){this.B=a;this.g.clear();this.A=this.o;this.o.reset(a,0);this.C.reset(a,1)};a2.prototype.reset=function(){};g.r(b2,a2);b2.prototype.o=function(a){var b=[];this.g||(this.g=D1(this.l),b.push(this.g));a=Array.from(a.firstChild.childNodes);a=g.p(a);for(var c=a.next();!c.done;c=a.next())d2(c.value,this.g.id,b);return b};g.r(f2,a2);
f2.prototype.o=function(a){var b=[];this.g||(this.g=D1(),this.l[this.g.id]=this.g,b.push(this.g));for(a=a.firstChild.firstChild;a;){switch(a.tagName){case "window":var c=a,d=c.getAttribute("id");a:{var e=c,f=this.l[d];if(e.getAttribute("t")||e.getAttribute("start")){c=e.getAttribute("start")?1E3*(0,window.parseFloat)(e.getAttribute("start")):(0,window.parseInt)(e.getAttribute("t"),10);f&&(f.end>=c?f.end=c:f=null);switch(e.getAttribute("op")){case "kill":c=null;break a;case "define":f=null}f||(f=D1());
var k={};f&&(g.Ma(k,f.params),f=f.params.Ma)&&(k.Ma={},g.Ma(k.Ma,f));e.getAttribute("rc")&&(k.jm=(0,window.parseInt)(e.getAttribute("rc"),10));e.getAttribute("cc")&&(k.hn=(0,window.parseInt)(e.getAttribute("cc"),10));e.getAttribute("ap")&&(f=(0,window.parseInt)(e.getAttribute("ap"),10),k.ne=0>f||8<f?7:f);e.getAttribute("ah")&&(k.Id=(0,window.parseInt)(e.getAttribute("ah"),10));e.getAttribute("av")&&(k.He=(0,window.parseInt)(e.getAttribute("av"),10));e.getAttribute("vs")&&(k.isVisible=!!e.getAttribute("vs"));
e.getAttribute("ju")&&(k.textAlign=(0,window.parseInt)(e.getAttribute("ju"),10));e.getAttribute("pd")&&(k.gi=1,0==(0,window.parseInt)(e.getAttribute("pd"),10)&&(k.gi=0));e.getAttribute("bc")&&(k.Ma||(k.Ma={}),k.Ma.backgroundColor=e.getAttribute("bc"));e.getAttribute("bo")&&(k.Ma||(k.Ma={}),k.Ma.backgroundOpacity=(0,window.parseInt)(e.getAttribute("bo"),10)/100);e.getAttribute("fc")&&(k.Ma||(k.Ma={}),k.Ma.color=e.getAttribute("fc"));e.getAttribute("sd")&&(k.yL=(0,window.parseInt)(e.getAttribute("sd"),
10));f=(0,window.parseInt)(e.getAttribute("d"),10)||1E3*(0,window.parseFloat)(e.getAttribute("dur"))||0x8000000000000;e=e.getAttribute("id")||"_"+C1++;c=new B1(c,f,0,e,k)}else c=null}this.l[d]=c;b.push(c);break;case "text":for(d=[],d2(a,this.g.id,d),d=g.p(d),c=d.next();!c.done;c=d.next())c=c.value,this.l[c.windowId]&&b.push(c)}a=a.nextSibling}return b};g.r(g2,a2);g2.prototype.reset=function(){this.G={};this.l=this.g=null;this.D=!0};
g2.prototype.o=function(a,b){a.firstChild.getAttribute("format");b=b||0;Number.isFinite(b);var c=Array.from(a.firstChild.childNodes);c=g.p(c);for(var d=c.next();!d.done;d=c.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "head":var e=d;break;case "body":var f=d}if(e)for(e=Array.from(e.childNodes),e=g.p(e),c=e.next();!c.done;c=e.next())if(c=c.value,1==c.nodeType)switch(c.tagName){case "pen":d=c.getAttribute("id");var k=this.A,l={},m=c.getAttribute("p");m&&g.Ma(l,this.A[m]);m=i2(c,"b");null!=
m&&(l.bold=m);m=i2(c,"i");null!=m&&(l.Wd=m);m=i2(c,"u");null!=m&&(l.underline=m);m=j2(c,"et");null!=m&&(l.charEdgeStyle=m);m=j2(c,"of");null!=m&&(l.offset=m);m=k2(c,"bc");null!=m&&(l.background=m);m=k2(c,"ec");null!=m&&(l.Kr=m);m=k2(c,"fc");null!=m&&(l.color=m);m=j2(c,"fs");void 0!=m&&0!=m&&(l.fontFamily=m);m=h2(c,"sz");void 0!=m&&(l.fontSizeIncrement=m/100-1);m=h2(c,"bo");void 0!=m&&(l.backgroundOpacity=m/255);c=h2(c,"fo");void 0!=c&&(l.textOpacity=c/255);k[d]=l;break;case "ws":d=c.getAttribute("id");
this.J[d]=l2(this,c);break;case "wp":d=c.getAttribute("id"),this.I[d]=m2(this,c)}if(f){e=b;c=[];f=Array.from(f.childNodes);f=g.p(f);for(d=f.next();!d.done;d=f.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "w":this.g=n2(this,d,e,!1);(d=this.G[this.g.id])&&d.end>this.g.start&&(d.end=this.g.start);this.G[this.g.id]=this.g;c.push(this.g);break;case "p":var n=e;k=[];l=d.getAttribute("w")||this.B;m=!!i2(d,"a");n=(h2(d,"t")||0)+n;var q=h2(d,"d")||5E3;m||(!this.D&&this.l&&this.l.windowId==l&&this.l.end>
n&&(this.l.end=n),this.l&&"\n"==this.l.text&&(this.l.text=""));var u=m?6:5,w=this.A[d.getAttribute("p")],H=d.childNodes;H.length&&(this.D=null!=d.getAttribute("d"));for(var F=0;F<H.length;F++){var M=H[F];0<F&&(m=!0);var Z=void 0;1==M.nodeType&&(Z=M);if(Z&&"s"==Z.tagName){var pa=Z;M=n;Z=q;var $a=l,sb=m,ke=u,Mh=pa.textContent?pa.textContent:"",Uf=this.A[pa.getAttribute("p")];pa=h2(pa,"t")||0;M=new A1(M+pa,Z-pa,ke,$a,Mh,sb,Uf)}else M=new A1(n,q,u,l,M.textContent||"",m,w);k.push(M);this.l=M}if(0<k.length)for(k[0].windowId==
this.B&&(this.g=n2(this,d,e,!0),c.push(this.g)),d=g.p(k),k=d.next();!k.done;k=d.next())k=k.value,k.windowId=this.g.id,this.g.l.push(k),c.push(k)}e=c}else e=[];return e};g.r(o2,I1);o2.prototype.B=function(a,b,c,d,e){if(c<d){var f="_"+C1++;c=c/1E3-this.D;d=d/1E3-this.D;a=new B1(c,d-c,5,f,{textAlign:0,ne:0,Id:2.5*b,He:5.33*a});e=new A1(c,d-c,5,f,e);this.o.push(a);this.o.push(e)}};
g.r(r2,a2);r2.prototype.o=function(a){a=new o2(a,a.byteLength,this.l);if(s2(a)){for(;a.g<a.l.byteLength;)for(0==a.version?a.A=q2(a)*(1E3/45):1==a.version&&(a.A=4294967296*q2(a)+q2(a)),a.C=p2(a);0<a.C;a.C--){var b=p2(a),c=p2(a),d=p2(a);b&4&&(b&3)==this.track&&(0==this.track||1==this.track)&&(b=this.g,b.g.push({time:a.A,type:this.track,Er:c,Gr:d,order:b.g.length}))}cka(this.g,a);return a.o}return[]};
r2.prototype.reset=function(){this.g.clear()};g.r(w2,a2);
w2.prototype.o=function(a,b){for(var c=[],d=a.split(ska),e=1;e<d.length;e++){var f=d[e],k=b;if(""!=f&&!tka.test(f)){var l=$2.exec(f);if(l&&4<=l.length){var m=y2(l[1]),n=y2(l[2])-m;m+=k;var q,u=q=void 0,w=void 0,H=void 0,F=l[3];l={textAlign:2};F=g.p(F?F.split(" "):[]);for(var M=F.next();!M.done;M=F.next())if(M=M.value.split(":"),2==M.length){var Z=M[1];switch(M[0]){case "line":M=Z.split(",");M[0].endsWith("%")&&(H=M[0],l.He=Number.parseInt(H,10),2==M.length&&(w=M[1].trim()));break;case "position":M=Z.split(",");
u=M[0];l.Id=Number.parseInt(u,10);2==M.length&&(q=M[1].trim());break;case "align":switch(Z){case "start":l.textAlign=0;break;case "middle":l.textAlign=2;break;case "end":l.textAlign=1}}}H||(l.He=100,w||(w="end"));if(!u)switch(l.textAlign){case 0:l.Id=0;break;case 1:l.Id=100;break;default:l.Id=50}u=0;switch(w){case "center":u+=3;break;case "end":u+=6;break;default:u+=0}switch(q){case "line-left":u+=0;break;case "center":u+=1;break;case "line-right":u+=2;break;default:switch(l.textAlign){case 0:u+=
0;break;case 2:u+=1;break;case 1:u+=2}}l.ne=0>u||8<u?7:u;q=l;f=f.substring($2.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");u=q;q=f;f={};if(0>q.indexOf("<")&&0>q.indexOf("&"))k=z2(m,n,5,u),n=new A1(m,n,5,k.id,q,!1,g.lc(f)?void 0:f),c.push(k),c.push(n),k.l.push(n);else for(w=q.split(uka),1==w.length?(q=5,u=z2(m,n,q,u)):(H=q=6,u=Object.assign({hn:32},u),u=new B1(m,n,H,"_"+C1++,u)),c.push(u),H=m,l=0;l<w.length;l++)F=w[l],0==l%2?(M=g.nq("<html>"+F+"</html>"),M.getElementsByTagName("parsererror").length?
(Z=M.createElement("span"),Z.appendChild(M.createTextNode(F))):Z=M.firstChild,x2(this,H,n-(H-m),q,u,0<l,Z,f,c)):H=y2(F)+k}$2.lastIndex=0}}return c};
var tka=/^NOTE/,ska=/(?:\r\n|\r|\n){2,}/,$2=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),uka=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.r(A2,g.G);A2.prototype.trackCount=function(){return u2(this.l,!0).length};
A2.prototype.dd=function(){this.g=null};
A2.prototype.U=function(){g.G.prototype.U.call(this);this.dd()};
A2.prototype.Sw=function(){return!1};g.r(C2,A2);g.h=C2.prototype;g.h.xo=function(a,b){var c=this.Ni(a),d=(0,g.A)(function(c){this.o=null;b(c.responseText,a)},this);
this.dd();this.o=g.as(c,{format:"RAW",onSuccess:d,withCredentials:!0})};
g.h.yo=function(a,b,c,d){this.A=c;if(d)for(b=g.p(d.captionTracks),c=b.next();!c.done;c=b.next())v2(this.l,c.value);a()};
g.h.Ni=function(a){var b=a.vb(),c={};if(this.A||a.o)c.fmt=this.A||"srv"+a.o;a.g&&(c.tlang=a.g.languageCode);return g.Sr(b,c)};
g.h.dd=function(){A2.prototype.dd.call(this);this.o&&this.o.abort()};
g.h.U=function(){this.dd();A2.prototype.U.call(this)};D2.prototype.contains=function(a){a=g.lb(this.Sa,a);return 0<=a||0>a&&1==(-a-1)%2};
D2.prototype.length=function(){return this.Sa.length/2};g.r(E2,g.G);g.h=E2.prototype;g.h.U=function(){g.G.prototype.U.call(this);this.o&&this.o.cancel()};
g.h.Wu=function(a){var b=this;if(this.G.zh())var c=this.B.L(this.A,"progresssync",function(){b.G.index.Fb()&&(b.reset(),b.g=null,F2(b,b.A.getCurrentTime()),b.B.Ja(c))});
else F2(this,a)};
g.h.reset=function(){this.C=new D2;this.o&&(this.o.cancel(),this.o=null)};
g.h.Yt=function(){var a;if(a=null!==this.g)a=this.g,a=a.g.jf(a);!a||this.o||this.g&&30<this.g.startTime-this.A.getCurrentTime()||(a=this.g,a=a.g.Eh(a),!g.S(g.V(this.A).experiments,"disable_captions_unknown_requests")&&!a.g[0].duration)||(this.C.contains(a.g[0].oa)||G2(this,a),this.g=g.Oa(a.g));this.J.start()};
g.h.yJ=function(a){var b=!(this.D?a.response:a.responseText)||400<=a.status;if(!g.S(g.V(this.A).experiments,"disable_captions_redirects_redux")){var c=g.az(a);if(c){a=g.Ey(this.l,this.M,{});b=this.l;g.Ay(b.l,a,c);b.requestId=a.get("req_id");G2(this,this.l);return}}b||null===this.I||(this.D?this.I(a.response,1E3*this.l.g[0].startTime,this.l.g[0].oa):this.I(a.responseText,1E3*this.l.g[0].startTime,this.l.g[0].oa));this.o=this.l=null};g.r(H2,A2);g.h=H2.prototype;g.h.xo=function(a,b){this.dd();var c=lka(this,a.l);if(c){var d=c.index.Mk(c.index.Sd());g.S(g.V(this.A).experiments,"html5_disable_caption_starttime")||(d-=c.index.Yc(c.index.Sd()));d*=1E3;var e=g.V(this.A).Ha;this.B=new E2(new g.iy,this.A,c,function(c,e,l){b(c,a,e,d,l)},e||g.Jv(c.info),(0,g.A)(function(){this.B&&this.B.reset();
this.g&&this.g.reset();this.C=!0},this))}};
g.h.Sw=function(){var a=this.C;this.C=!1;return a};
g.h.yo=function(a){if(g.V(this.A).Ha)v2(this.l,new g.vv({format:1,languageCode:"rawcc",languageName:"CC1",name:"",is_servable:!0,is_default:!0,is_translateable:!1})),v2(this.l,new g.vv({format:1,languageCode:"rawcc",languageName:"CC3",name:"",is_servable:!0,is_default:!0,is_translateable:!1}));else for(var b in this.o.g){var c=this.o.g[b];if(g.Nv(c.info.mimeType)&&"rawcc"!=b&&("386"!=b||!g.S(g.V(this.A).experiments,"html5_manifestless_captions_fmt3_killswitch"))){var d="en",e="English",f=".en";if(c=
c.info.captionTrack)d=c.languageCode,e=c.displayName,f=c.vssId;v2(this.l,new g.vv({format:1,languageCode:d,languageName:e,name:"",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:f}))}}a()};
g.h.dd=function(){A2.prototype.dd.call(this);this.B&&(this.B.dispose(),this.B=null)};
g.h.Ni=function(){return""};
g.h.U=function(){this.dd();A2.prototype.U.call(this)};g.r(J2,F1);J2.prototype.Um=function(a){var b=this.D.l;F1.prototype.Um.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.l==e)var d=f;else{d={};g.Ma(d,c.l);g.Ma(d,vka);var e=c.l;var f=d}H1(this,c,d)}};
var vka={bo:!0};g.r(K2,F1);g.h=K2.prototype;g.h.vx=function(){g.vq(this.X)};
g.h.DJ=function(){g.kq(this.element,"ytp-rollup-mode");this.Ug(this.pa,!0)};
g.h.Ls=function(){return this.J};
g.h.Ks=function(){return this.D.params.jm*L2(this)};
g.h.Ug=function(a,b){this.pa=a;if(L2(this)){for(var c=0,d=0;d<this.A.length&&c<a.length;d++)this.A[d]==a[c]&&c++;0<c&&c<a.length&&(a=this.A.concat(a.slice(c)));c=this.J;this.J=0;F1.prototype.Ug.call(this,a);d=this.o.offsetWidth+1;this.J=Math.max(mka(this),c,d);c=this.D.params.jm*L2(this)-this.o.offsetHeight;c!=this.T&&(b||(0,window.isNaN)(this.T)||(g.J(this.element,"ytp-rollup-mode"),g.uq(this.X)),g.Kh(this.o,"transform",c?"translateY("+c+"px)":""),this.T=c);F1.prototype.Ug.call(this,a)}else F1.prototype.Ug.call(this,
a)};g.r(M2,A2);g.h=M2.prototype;g.h.xo=function(a,b){var c=this.Ni(a),d=(0,g.A)(function(c){this.o=null;b(c.responseText,a)},this);
this.dd();this.o=g.as(c,{format:"RAW",onSuccess:d,withCredentials:!0})};
g.h.yo=function(a,b,c){var d=this.B;b={type:"list",tlangs:1,v:this.A,fmts:Number(b||!1),vssids:1};this.Dt&&(b.asrs=1);d=g.Sr(d,b);b=(0,g.A)(function(b){this.o=null;if((b=b.responseXML)&&b.firstChild){for(var d=this.l,e=g.p(b.getElementsByTagName("track")),l=e.next();!l.done;l=e.next()){var m=l.value;l=m.getAttribute("formats");var n=m.getAttribute("lang_code"),q=m.getAttribute("lang_translated"),u=m.getAttribute("name"),w=m.getAttribute("kind"),H=m.getAttribute("id"),F="true"==m.getAttribute("lang_default"),
M="true"==m.getAttribute("cantran");m=m.getAttribute("vss_id");v2(d,new g.vv({formats:l,format:c,languageCode:n,languageName:q,name:u,kind:w,id:H,is_servable:!0,is_translateable:M,vss_id:m,is_default:F}))}b=b.getElementsByTagName("target");d=b.length;for(e=0;e<d;e++)l=b[e].getAttribute("lang_code"),n=b[e].getAttribute("lang_translated"),q=b[e].getAttribute("lang_original"),u=b[e].getAttribute("id"),w="true"==b[e].getAttribute("lang_default"),l={languageCode:l,languageName:n,languageOriginal:q,id:u,
is_default:w},this.C[l.languageCode]=l.languageName,this.D.push(new g.uv(l))}a()},this);
this.dd();this.o=g.as(d,{format:"RAW",onSuccess:b,withCredentials:!0})};
g.h.Ni=function(a){var b=this.B,c={v:this.A,type:"track",lang:a.l,name:a.C,kind:a.B,fmt:a.o};a.g&&(c.tlang=y1(a));return b=g.Sr(b,c)};
g.h.dd=function(){A2.prototype.dd.call(this);this.o&&this.o.abort()};
g.h.U=function(){this.dd();A2.prototype.U.call(this)};g.r(P2,g.zK);g.h=P2.prototype;g.h.U=function(){if(this.D){var a=this.J.app.B;a&&a.lh()}else Z2(this,!1);g.zK.prototype.U.call(this)};
g.h.vu=function(){return this.D?!this.o.ra:this.ea||R2(this)?!0:Q2(this)};
g.h.load=function(a){g.zK.prototype.load.call(this);this.I=this.g.getAudioTrack();if(this.B||a)this.l&&(this.D&&!g.S(this.A.experiments,"disable_native_caption_api")?U2(this,!0):a?this.Hw(a,this.l):3!=this.g.Ca()&&this.B.xo(this.l,(0,g.A)(this.Hw,this))),this.l&&this.l!=S2(this)?this.g.ma("captionschanged",x1(this.l)):this.g.ma("onCaptionsTrackListChanged");else{var b;I2(this.o,this.J)?b=new H2(this.o.ka,this.g):this.o.captionTracks.length?b=new C2(this.o):b=new M2(this.o.kk,this.o.videoId,this.o.Cf||
this.A.Cf||g.tC(this.o,"yt:cc_default_lang")||this.A.ub,this.o.jk);this.B=b;b.yo((0,g.A)(this.fK,this),!0,this.D?"vtt":void 0,this.g.getAudioTrack())}};
g.h.unload=function(){this.D?g.S(this.A.experiments,"disable_native_caption_api")?this.J.app.B.lh():this.l&&U2(this,!1):(this.ca&&g.wq(this.ca),g.hK(this.g,"captions"),this.R=[],this.B&&this.B.dd(),this.M&&g.eK(this.g,this.M),this.uq());g.zK.prototype.unload.call(this);var a=g.W(this.g.app);a&&a.C&&g.MC(a.C.o);this.g.ma("captionschanged",{})};
g.h.fK=function(){var a;this.O||Q2(this)?a=T2(this,this.O):R2(this)&&(a=S2(this));if(this.D||this.ea){for(var b=u2(this.B.l,!0),c=[],d=0;d<b.length;d++){var e=b[d],f={kind:"subtitles",label:g.wv(e),srclang:y1(e),id:e.toString()};this.ea||(f.src=this.B.Ni(e));e==a&&(f["default"]=1);c.push(g.Xd("TRACK",f))}this.J.app.B.pi(c);(a=this.J.app.B.ia())&&a.textTracks&&a.textTracks.addEventListener&&!g.S(this.A.experiments,"disable_native_caption_api")&&this.ba.L(a.textTracks,"change",this.gK)}else!this.l&&
a&&W2(this,a),this.g.ma("onCaptionsTrackListChanged"),this.g.ma("onApiChange")};
g.h.gK=function(){for(var a=this.J.app.B.ia().textTracks,b=null,c=0;c<a.length;c++)if("showing"==a[c].mode)a:{b=u2(this.B.l,!0);for(var d=0;d<b.length;d++)if(b[d].toString()==a[c].id){b=b[d];break a}b=null}(this.loaded?this.l:null)!=b&&W2(this,b,!0)};
g.h.JL=function(){g.S(this.A.experiments,"disable_native_caption_api")?this.loaded&&!this.D&&this.unload():!this.l&&this.D||this.unload()};
g.h.Hw=function(a,b,c,d,e){a&&(this.B.Sw()&&(this.R=[],g.hK(this.J,"captions"),this.fa.Pi()),a=kka(this.B,a,b,c,d),g.S(this.A.experiments,"debug_web_player_live_captions_segment_numbers")&&c&&e&&(c=a.reduce(function(a,b){return b.start<a?b.start:a},Number.MAX_SAFE_INTEGER),b=a.reduce(function(a,b){return b.end>a?b.end:a},c)-c,d=new B1(c,b,0,"_"+C1++,{ne:2,
Id:100,He:0}),a.push(d),e=new A1(c,b,0,d.id,"sq="+e),a.push(e)),g.eK(this.g,a),this.O&&!this.ea&&nka(this),this.O=!1)};
g.h.cD=function(a){this.R.push(a);this.fa.Pi()};
g.h.dD=function(a){g.Za(this.R,a);var b=I2(this.o,this.J)&&this.A.Ha;!g.S(this.A.experiments,"disable_remove_displayed_close_caption_cue")&&b&&g.gK(this.g,[a]);this.fa.Pi()};
g.h.QK=function(a){if(a instanceof B1){var b=this.T[a.id];b&&b.D!=a&&(b.dispose(),delete this.T[a.id],b=null);b||(b=oka(this,a))&&(this.T[a.id]=b)}else b=a.windowId,this.Y[b]||(this.Y[b]=[]),this.Y[b].push(a)};
g.h.ZK=function(){Y2(this,this.Z);this.Z=null};
g.h.Ay=function(){this.fa.stop();g.mc(this.Y);this.R.sort(g.XD);var a=this.R;if(this.M){var b=(0,g.fe)(a,function(a){return-1==this.M.indexOf(a)},this);
b.length&&(a=b)}(0,g.C)(a,this.QK,this);g.Zb(this.T,function(a,b){this.Y[b]?(a.element.parentNode||g.lK(this.g,a.element,4),a.Ug(this.Y[b])):(a.dispose(),delete this.T[b])},this)};
g.h.tx=function(){N2(this,{},!0)};
g.h.In=function(){var a=X2.Ma;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.Wd?3:a.bold?1:a.Wd?2:0,textOpacity:a.textOpacity,windowColor:X2.windowColor,windowOpacity:X2.windowOpacity};var b=O2(this,"display-settings"),c;for(c in b)null!=b[c]&&(a[c]=b[c]);return a};
g.h.yq=function(a,b){var c={};g.Ma(c,O2(this,"display-settings"));g.Ma(c,a);N2(this,c,b);this.g.P("captionssettingschanged")};
g.h.uq=function(){!this.D&&this.loaded&&(g.Zb(this.T,function(a,b){a.dispose();delete this.T[b]},this),this.Ay())};
g.h.Lo=function(a,b){switch(a){case "fontSize":if((0,window.isNaN)(b))break;var c=g.ud(b,-2,4);this.yq({fontSizeIncrement:c});return c;case "reload":b&&!this.D&&W2(this,this.l,!0);break;case "stickyLoading":void 0!=b&&this.A.Ya&&V2(this,"module-enabled",!!b);break;case "track":if(!this.B)return{};if(b){if(this.D)break;if(!g.Fa(b))break;if(g.lc(b)){W2(this,null,!0);break}var d;c=u2(this.B.l,!0);for(var e=0;e<c.length;e++){var f=c[e];f.l!=b.languageCode||d&&f.A!=b.languageName||(d=b.translationLanguage?
Xja(f,b.translationLanguage):f)}!d||d==this.l&&this.loaded||W2(this,d,!0)}else return this.loaded&&this.l&&this.l!=S2(this)?x1(this.l):{};return"";case "tracklist":return this.B?(0,g.E)(u2(this.B.l,!(!b||!b.includeAsr)),function(a){return x1(a)}):[];
case "translationLanguages":return this.B?this.B.D:[];case "displaySettings":d=this.In();if(g.kA(this.A)&&b&&g.Fa(b))if(b.reset)this.tx();else{f={};for(c in b)switch(c){case "color":case "background":case "windowColor":f[c]=pka(b[c],d[c]);break;case "textOpacity":case "backgroundOpacity":case "windowOpacity":f[c]=qka(b[c],d[c]);break;case "charEdgeStyle":var k=g.rX[b[c]];f[c]=g.va(k)?k:d[c];break;case "fontSizeIncrement":f[c]=rka(b[c],d[c]);break;case "fontFamilyOption":k=g.qX[b[c]];f.fontFamily=
g.va(k)?k:d[c];break;case "fontStyle":k=g.sX[b[c]],f[c]=g.va(k)?k:d[c]}for(e in f)f[e+"Override"]=!0;this.yq(f,!0);d=this.In()}d.fontFamilyOption=g.pha[d.fontFamily];d.charEdgeStyle=g.qha[d.charEdgeStyle];d.fontStyle=g.rha[d.fontStyle];return d;case "sampleSubtitles":this.D||void 0==b||Z2(this,!!b);break;case "xmlTrack":b&&this.A.Ya&&(this.D||W2(this,new g.vv({languageName:b.name}),!1,b.xml))}};
g.h.aD=function(){var a="reload fontSize track tracklist translationLanguages displaySettings sampleSubtitle".split(" ");this.A.Ya&&a.push("stickyLoading","xmlTrack");return a};
g.h.bD=function(){var a=this.l;return a?{cc:a.D}:{}};
g.h.ny=function(){this.loaded&&this.l&&this.l!=S2(this)?(V2(this,"module-enabled",!1),this.unload(),R2(this,!0)&&W2(this,S2(this),!1)):W2(this,this.l==S2(this)?T2(this,!0):this.l,!0)};
g.h.ZG=function(){var a=this.l==S2(this);R2(this,a)?W2(this,this.g.getAudioTrack().Ek,!1):this.o.captionTracks.length&&(this.loaded&&this.unload(),this.vu()&&(a?W2(this,T2(this),!1):this.load()))};g.HQ.captions=P2;})(_yt_player);
