(function(g){var window=this;var a3=function(a,b,c,d){var e=b.sb();g.K(a.element,"ytp-suggestion-set",!!e.videoId);var f=b.getPlaylistId();d=b.qc(c,d?d:"mqdefault.jpg");var k=b instanceof g.$B?g.SO(b.lengthSeconds):null,l=!!f;f=l&&"RD"==(new g.YD(f.substr(0,2),f.substr(2))).type;var m=b instanceof g.$B?b.ra:null;c={title:b.title,author:b.author,author_and_views:e.shortViewCount?b.author+" \u2022 "+e.shortViewCount:b.author,aria_label:b.ri||g.Q("YTP_WATCH_VIDEO_OR_PLAYLIST",{TITLE:b.title},b.title),duration:k,url:b.Oi(c),is_live:m,
is_list:l,is_mix:f,background:d?"background-image: url("+d+")":""};b instanceof g.$D&&(c.playlist_length=b.getLength());a.update(c)},b3=function(a,b){g.dv.call(this,{F:"div",
W:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.l=a;this.created=!1},c3=function(a){g.R.call(this,{F:"div",
H:"ytp-upnext",N:{"aria-label":"{{aria_label}}"},K:[{F:"div",H:"ytp-cued-thumbnail-overlay-image",N:{style:"{{background}}"}},{F:"span",H:"ytp-upnext-top",K:[{F:"span",H:"ytp-upnext-header",V:"Up Next"},{F:"span",H:"ytp-upnext-title",V:"{{title}}"},{F:"span",H:"ytp-upnext-author",V:"{{author}}"}]},{F:"a",H:"ytp-upnext-autoplay-icon",N:{role:"button",href:"{{url}}","aria-label":"Play next video"},K:[{F:"svg",N:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},K:[{F:"circle",H:"ytp-svg-autoplay-circle",
N:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{F:"circle",H:"ytp-svg-autoplay-ring",N:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{F:"path",H:"ytp-svg-fill",N:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{F:"span",H:"ytp-upnext-bottom",K:[{F:"span",H:"ytp-upnext-cancel"},{F:"span",H:"ytp-upnext-paused",V:"Autoplay is paused"}]}]});this.A=null;var b=
this.g["ytp-upnext-cancel"];this.A=new g.R({F:"button",W:["ytp-upnext-cancel-button","ytp-button"],N:{tabindex:"0","aria-label":"Cancel autoplay"},V:"Cancel"});g.I(this,this.A);this.A.da("click",this.eH,this);this.A.aa(b);this.l=a;this.J=this.g["ytp-svg-autoplay-ring"];this.D=this.C=this.o=this.B=null;this.G=new g.L(this.pk,5E3,this);g.I(this,this.G);this.I=0;this.L(this.g["ytp-upnext-autoplay-icon"],"click",this.YI);this.Yv();this.L(a,"autonavvisibility",this.Yv);this.L(a,"mdxnowautoplaying",this.lI);
this.L(a,"mdxautoplaycanceled",this.mI);this.L(a,"mdxautoplayupnext",this.Ey);3==this.l.Ca()&&(a=(a=g.OJ(g.JJ(this.l)))?a.WA():null)&&this.Ey(a)},d3=function(a,b){a.B=b;
a3(a,b,g.V(a.l),"hqdefault.jpg")},e3=function(a,b){if(!a.o){g.Gt("a11y-announce","Up Next "+a.B.title);
a.I=g.P();a.o=new g.L((0,g.A)(a.Tm,a,b),25);a.Tm(b);var c=b||g.T(g.V(a.l).experiments,"autoplay_time")||1E4;a.l.ma("onAutonavCoundownStarted",c)}g.kq(a.element,"ytp-upnext-autoplay-paused")},g3=function(a){f3(a);
a.I=g.P();a.Tm();g.J(a.element,"ytp-upnext-autoplay-paused")},f3=function(a){a.o&&(a.o.dispose(),a.o=null)},h3=function(a,b){b=void 0===b?!1:b;
var c=g.V(a.l);if(g.S(c.experiments,"autonav_notifications")&&b&&window.Notification&&window.document.hasFocus){var d=window.Notification.permission;"default"==d?window.Notification.requestPermission():"granted"!=d||window.document.hasFocus()||(d=a.B.sb(),a.pk(),a.C=new window.Notification("Up Next",{body:d.title,icon:d.qc(c)}),a.D=a.L(a.C,"click",a.OI),a.G.start())}f3(a);a.l.Mh(!1,b)},i3=function(a){b3.call(this,a,"subscribecard-endscreen");
var b=a.getVideoData();this.o=new g.R({F:"div",H:"ytp-subscribe-card",K:[{F:"img",H:"ytp-author-image",N:{src:b.profilePicture}},{F:"div",H:"ytp-subscribe-card-right",K:[{F:"div",H:"ytp-author-name",V:b.author},{F:"div",H:"html5-subscribe-button-container"}]}]});g.I(this,this.o);this.o.aa(this.element);this.A=new g.qU("Subscribe",null,"Unsubscribe",null,!0,!1,b.je,b.subscribed,"trailer-endscreen",null,null,a);g.I(this,this.A);this.A.aa(this.o.g["html5-subscribe-button-container"]);this.hide()},j3=
function(a){var b=g.V(a),c=g.nw||g.Qh?{style:"will-change: opacity"}:void 0,d=b.g,e=["ytp-videowall-still"];
b.l&&e.push("ytp-videowall-show-text");g.R.call(this,{F:"a",W:e,N:{href:"{{url}}",target:d?"_blank":"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},K:[{F:"div",H:"ytp-videowall-still-image",N:{style:"{{background}}"}},{F:"span",H:"ytp-videowall-still-info",K:[{F:"span",H:"ytp-videowall-still-info-bg",K:[{F:"span",H:"ytp-videowall-still-info-content",N:c,K:[{F:"span",H:"ytp-videowall-still-info-title",V:"{{title}}"},{F:"span",H:"ytp-videowall-still-info-author",
V:"{{author_and_views}}"},{F:"span",H:"ytp-videowall-still-info-live",V:"Live"},{F:"span",H:"ytp-videowall-still-info-duration",V:"{{duration}}"}]}]}]},{F:"span",W:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],K:[{F:"span",H:"ytp-videowall-still-listlabel-icon"},"Playlist",{F:"span",H:"ytp-videowall-still-listlabel-length",K:[" (",{F:"span",V:"{{playlist_length}}"},")"]}]},{F:"span",W:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],K:[{F:"span",H:"ytp-videowall-still-listlabel-mix-icon"},
"Mix",{F:"span",H:"ytp-videowall-still-listlabel-length",V:" (50+)"}]}]});this.B=d;this.l=a;this.o=null;this.A=new g.nt(this);g.I(this,this.A);this.da("click",this.D);this.da("keypress",this.G);this.A.L(a,"videodatachange",this.C);g.V(a).C&&g.tL(a.app.T,this.element,this);this.C()},k3=function(a){g.pK(a.l,a.element);
var b=a.o.sb().videoId,c=a.o.getPlaylistId();g.fW(a.l.app,b,a.o.bd,c,void 0,void 0,void 0)},l3=function(a){b3.call(this,a,"videowall-endscreen");
this.M=a;this.D=0;this.A=[];this.G=this.C=this.B=null;this.I=this.R=!1;this.ba=new g.nt(this);g.I(this,this.ba);this.J=new g.L(g.La(g.J,this.element,"ytp-show-tiles"),0);g.I(this,this.J);var b=new g.R({F:"button",W:["ytp-button","ytp-endscreen-previous"],N:{"aria-label":"Previous"},K:[g.mO()]});g.I(this,b);b.aa(this.element);b.da("click",this.PE,this);this.O=new g.Yu({F:"div",H:"ytp-endscreen-content"});g.I(this,this.O);this.O.aa(this.element);b=new g.R({F:"button",W:["ytp-button","ytp-endscreen-next"],
N:{"aria-label":"Next"},K:[g.nO()]});g.I(this,b);b.aa(this.element);b.da("click",this.OE,this);this.o=new c3(a);g.I(this,this.o);g.lK(this.l,this.o.element,4);this.hide()},m3=function(a){return g.mK(a.l)&&a.yr()&&!a.G},n3=function(a,b){return(0,g.E)(b.suggestions,function(b){b=g.PQ(b);
g.I(a,b);return b})},o3=function(a){var b=a.ip();
b!=a.R&&(a.R=b,a.l.P("autonavvisibility"))},q3=function(a){g.zK.call(this,a);
this.l=null;this.o=new g.nt(this);g.I(this,this.o);this.A=g.V(a);p3(a)?this.l=new l3(this.g):this.A.Fa?this.l=new i3(this.g):this.l=new b3(this.g);g.I(this,this.l);g.lK(this.g,this.l.element,4);this.rx();this.o.L(a,"videodatachange",this.rx,this);this.o.L(a,"crn_endscreen",this.SC,this);this.o.L(a,"crx_endscreen",this.TC,this)},p3=function(a){a=g.V(a);
return a.Mc&&!a.Fa};
g.r(b3,g.dv);b3.prototype.create=function(){this.created=!0};
b3.prototype.hp=function(){this.created=!1};
b3.prototype.yr=function(){return!1};
b3.prototype.ip=function(){return!1};g.r(c3,g.R);g.h=c3.prototype;g.h.pk=function(){this.C&&(this.G.stop(),this.Ja(this.D),this.D=null,this.C.close(),this.C=null)};
g.h.Yv=function(){g.cv(this,g.KJ(this.l))};
g.h.OI=function(){window.focus();this.pk()};
g.h.hide=function(){g.R.prototype.hide.call(this)};
g.h.Tm=function(a){a=a||g.T(g.V(this.l).experiments,"autoplay_time")||1E4;var b=Math.min(g.P()-this.I,a);a=Math.min(b/a,1);this.J.setAttribute("stroke-dashoffset",-211*(a+1));1<=a&&3!=this.l.Ca()?h3(this,!0):this.o&&this.o.start()};
g.h.YI=function(a){!g.le(this.A.element,g.ct(a))&&g.yQ(a,this.l)&&h3(this)};
g.h.eH=function(){g.MJ(this.l,!0)};
g.h.lI=function(a){this.l.Ca();this.show();e3(this,a)};
g.h.Ey=function(a){this.l.Ca();this.B&&this.B.sb().videoId==a.sb().videoId||d3(this,a)};
g.h.mI=function(){this.l.Ca();f3(this);this.hide()};
g.h.U=function(){f3(this);this.pk();g.R.prototype.U.call(this)};g.r(i3,b3);g.r(j3,g.R);j3.prototype.D=function(a){g.yQ(a,this.l,this.B,this.o.bd||void 0)&&k3(this)};
j3.prototype.G=function(a){switch(a.keyCode){case 13:case 32:g.ht(a)||(k3(this),g.gt(a))}};
j3.prototype.C=function(){var a=this.l.getVideoData(),b=g.V(this.l);this.B=a.isDni?!1:b.g};g.r(l3,b3);g.h=l3.prototype;g.h.create=function(){b3.prototype.create.call(this);var a=this.l.getVideoData();a&&(this.B=n3(this,a),this.C=a);this.mf();this.ba.L(this.l,"appresize",this.mf);this.ba.L(this.l,"onVideoAreaChange",this.mf);this.ba.L(this.l,"videodatachange",this.QE);this.ba.L(this.l,"autonavchange",this.Tu);this.ba.L(this.l,"autonavcancel",this.NE);this.ba.L(this.element,"transitionend",this.hK)};
g.h.hp=function(){g.pt(this.ba);g.gf(this.A);this.A=[];this.B=null;b3.prototype.hp.call(this);g.kq(this.element,"ytp-show-tiles");this.J.stop()};
g.h.yr=function(){return 1!=this.C.autonavState};
g.h.show=function(){b3.prototype.show.call(this);g.kq(this.element,"ytp-show-tiles");g.V(this.l).l?g.vq(this.J):this.J.start();(this.I||this.G&&this.G!=this.C.clientPlaybackNonce)&&g.MJ(this.l,!1);m3(this)?(o3(this),2==this.C.autonavState?g.S(g.V(this.l).experiments,"fast_autonav_in_background")&&3==this.l.kf()?h3(this.o,!0):e3(this.o):3==this.C.autonavState&&g3(this.o)):(g.MJ(this.l,!0),o3(this))};
g.h.hide=function(){b3.prototype.hide.call(this);g3(this.o);o3(this)};
g.h.hK=function(a){g.ct(a)==this.element&&this.mf()};
g.h.mf=function(){if(this.B&&this.B.length){g.J(this.element,"ytp-endscreen-paginate");var a=g.bK(this.M,!0),b=g.rv(this.M);b&&(b=b.Hc()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.B.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<k);){var q=b/2,u=e/2,w=b<=f-2&&n>=u*m,H=e<=k-2&&n>=q*m;if((q+1)/u*d/c>c/(q/(u+1)*d)&&H)n-=q*m,e+=2;else if(w)n-=u*m,b+=2;else if(H)n-=q*m,e+=2;else break}d=
!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m*=c;n*=c;m*=g.ud(a.width/m||1,1,1.21);n*=g.ud(a.height/n||1,1,1.21);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.O.element;g.fi(a,m,n);g.Kh(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});d3(this.o,this.B[0]);g.K(this.element,"ytp-endscreen-takeover",m3(this));o3(this);m+=4;n+=4;for(f=c=0;f<b;f++)for(k=0;k<e;k++)if(q=c,u=0,d&&f>=b-2&&k>=e-2?u=1:0==k%2&&0==f%2&&(2>k&&2>
f?0==k&&0==f&&(u=2):u=2),q=g.vd(q+this.D,l),0!=u){w=this.A[c];w||(w=new j3(this.l),this.A[c]=w,a.appendChild(w.element));H=Math.floor(n*k/e);var F=Math.floor(m*f/b),M=Math.floor(n*(k+u)/e)-H-4,Z=Math.floor(m*(f+u)/b)-F-4;g.Vh(w.element,F,H);g.fi(w.element,Z,M);g.Kh(w.element,"transitionDelay",(k+f)/20+"s");g.K(w.element,"ytp-videowall-still-mini",1==u);g.K(w.element,"ytp-videowall-still-large",2<u);u=w;q=this.B[q];u.o!=q&&(u.o=q,a3(u,q,g.V(u.l),g.iq(u.element,"ytp-videowall-still-large")?"hqdefault.jpg":
"mqdefault.jpg"),q=(q=q.bd)&&q.itct)&&(w=u.l,g.V(w).C&&g.uL(w.app.T,u.element,q));c++}g.K(this.element,"ytp-endscreen-paginate",c<l);for(b=this.A.length-1;b>=c;b--)e=this.A[b],g.de(e.element),g.ff(e);this.A.length=c}};
g.h.QE=function(){var a=this.l.getVideoData();this.C!=a&&(this.D=0,this.B=n3(this,a),this.C=a,this.mf())};
g.h.OE=function(){this.D+=this.A.length;this.mf()};
g.h.PE=function(){this.D-=this.A.length;this.mf()};
g.h.ZB=function(){return!!this.o.o};
g.h.Tu=function(a){1==a?(this.I=!1,this.G=this.C.clientPlaybackNonce,f3(this.o),this.Ia()&&this.mf()):(this.I=!0,this.Ia()&&m3(this)&&(2==a?e3(this.o):3==a&&g3(this.o)))};
g.h.NE=function(a){if(a){for(a=0;a<this.A.length;a++)g.qK(this.M,this.A[a].element,!0);this.Tu(1)}else this.G=null,this.I=!1;this.mf()};
g.h.ip=function(){return this.Ia()&&m3(this)};g.r(q3,g.zK);g.h=q3.prototype;g.h.uu=function(){var a=this.g.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!p3(this.g)||b;a=g.xC(a,"ypc_module");var c=g.vV(this.g.app);return b&&!a&&!c};
g.h.tu=function(){return this.l.ip()};
g.h.WB=function(){return this.tu()?this.l.ZB():!1};
g.h.U=function(){g.hK(this.g,"endscreen");g.zK.prototype.U.call(this)};
g.h.load=function(){g.zK.prototype.load.call(this);this.l.show()};
g.h.unload=function(){g.zK.prototype.unload.call(this);this.l.hide();this.l.hp()};
g.h.SC=function(a){this.uu()&&(this.l.created||this.l.create(),"load"==a.getId()&&this.load())};
g.h.TC=function(a){"load"==a.getId()&&this.loaded&&this.unload()};
g.h.rx=function(){g.hK(this.g,"endscreen");var a=Math.max(1E3*(this.g.getVideoData().lengthSeconds-10),0);a=new g.VD(a,0x8000000000000,{id:"preload",namespace:"endscreen"});g.I(this,a);var b=new g.VD(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.I(this,b);g.eK(this.g,[a,b])};g.HQ.endscreen=q3;})(_yt_player);
