(function(g){var window=this;var k4=function(a){g.dv.call(this,{F:"div",H:"ytp-miniplayer-ui"});this.l=a;this.J=!1;this.G=this.C=this.A=void 0;this.L(a,"minimized",this.vI);this.L(a,"onStateChange",this.uL)},l4=function(a){g.zK.call(this,a);
this.l=new k4(this.g);this.l.hide();g.lK(this.g,this.l.element,4);a.app.I.g&&(this.load(),g.K(a.getRootNode(),"ytp-player-minimized",!0))};
g.r(k4,g.dv);g.h=k4.prototype;
g.h.show=function(){this.A=new g.rq(this.lD,null,this);this.A.start();if(!this.J){this.I=new g.wU(this.l,this);g.I(this,this.I);g.lK(this.l,this.I.element,4);this.R=new g.BR(this.l);g.I(this,this.R);this.D=new g.R({F:"div",H:"ytp-miniplayer-scrim"});g.I(this,this.D);this.D.aa(this.element);this.L(this.D.element,"click",this.Cw);var a=new g.R({F:"button",W:["ytp-miniplayer-close-button","ytp-button"],N:{"aria-label":g.Q("YTP_CLOSE")},K:[g.rO()]});g.I(this,a);a.aa(this.D.element);this.L(a.element,"click",
this.yu);this.B=new g.R({F:"div",H:"ytp-miniplayer-controls"});g.I(this,this.B);this.B.aa(this.D.element);this.L(this.B.element,"click",this.Cw);var b=new g.R({F:"div",H:"ytp-miniplayer-button-container"});g.I(this,b);b.aa(this.B.element);a=new g.R({F:"div",H:"ytp-miniplayer-play-button-container"});g.I(this,a);a.aa(this.B.element);var c=new g.R({F:"div",H:"ytp-miniplayer-button-container"});g.I(this,c);c.aa(this.B.element);this.O=new g.eT(this.l,this,!1);g.I(this,this.O);this.O.aa(b.element);b=new g.bT(this.l,
this);g.I(this,b);b.aa(a.element);this.M=new g.eT(this.l,this,!0);g.I(this,this.M);this.M.aa(c.element);this.G=new g.bU(this.l,this);g.I(this,this.G);this.G.aa(this.D.element);this.C=new g.kT(this.l,this);g.I(this,this.C);g.lK(this.l,this.C.element,4);this.o=new g.R({F:"div",H:"ytp-miniplayer-buttons"});g.I(this,this.o);g.lK(this.l,this.o.element,4);this.o.hide();a=new g.R({F:"button",W:["ytp-miniplayer-close-button","ytp-button"],N:{"aria-label":g.Q("YTP_CLOSE")},K:[g.rO()]});g.I(this,a);a.aa(this.o.element);
this.L(a.element,"click",this.yu);a=new g.R({F:"button",W:["ytp-miniplayer-replay-button","ytp-button"],N:{"aria-label":g.Q("YTP_CLOSE")},K:[g.AO()]});g.I(this,a);a.aa(this.o.element);this.L(a.element,"click",this.wJ);this.L(this.l,"presentingplayerstatechange",this.mD);this.L(this.l,"appresize",this.xb);this.L(this.l,"fullscreentoggled",this.xb);this.xb();this.J=!0}0!=this.l.sd()&&g.dv.prototype.show.call(this);this.C.show();this.l.jj("annotations_module")};
g.h.hide=function(){this.A&&(this.A.dispose(),this.A=void 0);g.dv.prototype.hide.call(this);this.l.app.I.g||(this.J&&this.C.hide(),this.l.Lh("annotations_module"))};
g.h.U=function(){this.A&&(this.A.dispose(),this.A=void 0);g.dv.prototype.U.call(this)};
g.h.yu=function(){this.l.rd();this.l.ma("onCloseMiniplayer")};
g.h.wJ=function(){this.l.Gb()};
g.h.Cw=function(a){if(a.target==this.D.element||a.target==this.B.element)g.wt("kevlar_miniplayer_scrim_pause")?2==this.l.sd()?this.l.Gb():this.l.Cb():this.l.ma("onExpandMiniplayer")};
g.h.vI=function(){g.K(this.l.getRootNode(),"ytp-player-minimized",this.l.app.I.g);this.l.app.I.g&&0==this.l.sd()?this.o.show():this.o.hide()};
g.h.lD=function(){g.mT(this.C);this.G.l();this.A.start()};
g.h.mD=function(a){g.U(a.state,32)&&this.I.hide()};
g.h.xb=function(){var a=this.C,b=g.QJ(this.l).Da().width;a.Na=0;a.B=b;a.D=!1;g.oT(a)};
g.h.uL=function(a){this.l.app.I.g&&(0==a?(this.hide(),this.o.show()):(this.show(),this.o.hide()))};
g.h.bb=function(){return this.I};
g.h.Hc=function(){return!1};
g.h.Ah=function(){return!1};
g.h.Nx=function(){};
g.h.uk=function(){};
g.h.vk=function(){};
g.h.ll=function(){return null};
g.h.Mo=function(){return new g.vh(0,0,0,0)};
g.h.No=function(){};
g.h.Rl=function(a,b,c){a.style.left="";a.style.top="";a.style.bottom="";b=g.hi(a);var d=g.QJ(this.l).Da().width;c=g.ud(c-b.width/2,0,d-b.width);a.style.bottom="25px";a.style.left=c+"px"};
g.h.nl=function(){};
g.h.Oo=function(){};g.r(l4,g.zK);l4.prototype.init=function(){};
l4.prototype.load=function(){this.g.Iu();this.l.show()};
l4.prototype.unload=function(){this.g.Ku();this.l.hide()};g.HQ.miniplayer=l4;})(_yt_player);
