(function(g){var window=this;var Dka=function(a,b){return g.ic(a,b)},m4=function(){},Eka=function(a){if(a.sc&&"function"==typeof a.sc)return a.sc();
if(g.v(a))return a.split("");if(g.Da(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.ec(a)},Fka=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Da(a)||g.v(a))(0,g.C)(a,b,void 0);else{if(a.nd&&"function"==typeof a.nd)var c=a.nd();else if(a.sc&&"function"==typeof a.sc)c=void 0;else if(g.Da(a)||g.v(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.fc(a);d=Eka(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},n4=function(a){g.Wo(a,"zx",g.Ob());
return a},o4=function(a,b,c){g.Ca(c)||(c=[String(c)]);
g.bp(a.o,b,c)},p4=function(a){if(!a.l&&"undefined"==typeof window.XMLHttpRequest&&"undefined"!=typeof window.ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new window.ActiveXObject(d),a.l=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.l},q4=function(a){var b;
(b=a.g)||(b={},p4(a)&&(b[0]=!0,b[1]=!0),b=a.g=b);return b},r4=function(a){return(a=p4(a))?new window.ActiveXObject(a):new window.XMLHttpRequest},s4=function(a,b){return b+" ["+a.X+" "+a.I+" "+a.getStatus()+"]"},Gka=function(a){return"content-type"==a.toLowerCase()},t4=function(a){a.g&&a.M&&(a.g.ontimeout=null);
a.D&&(g.x.clearTimeout(a.D),a.D=null)},Hka=function(a){return g.Rd&&g.Fc(9)&&g.va(a.timeout)&&g.t(a.ontimeout)},u4=function(a){a.T||(a.T=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},v4=function(a,b){if(a.g){t4(a);
var c=a.g,d=a.O[0]?g.za:null;a.g=null;a.O=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},w4=function(a,b){a.l=!1;
a.g&&(a.o=!0,a.g.abort(),a.o=!1);a.B=b;a.A=5;u4(a);v4(a)},x4=function(a){return a.g?a.g.readyState:0},y4=function(a){if(a.l&&"undefined"!=typeof g.wW)if(a.O[1]&&4==x4(a)&&2==a.getStatus())s4(a,"Local request error detected and ignored");
else if(a.G&&4==x4(a))g.Eg(a.Ys,0,a);else if(a.dispatchEvent("readystatechange"),4==x4(a)){s4(a,"Request complete");a.l=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.Wg(String(a.I))[1]||null;if(!f&&g.x.self&&g.x.self.location){var k=g.x.self.location.protocol;f=k.substr(0,k.length-1)}e=!Ika.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.A=6;try{var l=2<x4(a)?a.g.statusText:""}catch(m){l=""}a.B=l+" ["+a.getStatus()+"]";u4(a)}}finally{v4(a)}}},z4=function(a){g.Lf.call(this);
this.headers=new g.Jo;this.R=a||null;this.l=!1;this.O=this.g=null;this.X=this.I="";this.A=0;this.B="";this.o=this.Y=this.G=this.T=!1;this.C=0;this.D=null;this.fa="";this.M=this.Z=!1},A4=function(a){try{return a.g?a.g.responseText:""}catch(b){return""}},Jka=function(a,b){var c=[];
g.xl(b,function(a){try{var b=g.Tq.prototype.l.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.t(b)?g.Sq(b)&&c.push(a):c.push(a)},a);
return c},Kka=function(a,b){var c=Jka(a,b);
(0,g.C)(c,function(a){g.Tq.prototype.remove.call(this,a)},a)},B4=function(a){if(a.Lc){if(a.Lc.locationOverrideToken)return{locationOverrideToken:a.Lc.locationOverrideToken};
if(null!=a.Lc.latitudeE7&&null!=a.Lc.longitudeE7)return{latitudeE7:a.Lc.latitudeE7,longitudeE7:a.Lc.longitudeE7}}return null},Lka=function(a,b,c,d){var e=new g.Mo(null,void 0);
a&&g.No(e,a);b&&g.Oo(e,b);c&&g.Po(e,c);d&&(e.l=d);return e},C4=function(){this.g=[];
this.l=[]},D4=function(a){g.Ct[a]&&(a=g.Ct[a],(0,g.C)(a,function(a){g.At[a]&&delete g.At[a]}),a.length=0)},Mka=function(a){var b=g.zt();
if(b)if(b.clear(a),a)D4(a);else for(var c in g.Ct)D4(c)},E4=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.o=!1;this.capabilities=new window.Set;this.experiments=new window.Set;this.theme="u";new g.Jo;this.g=this.l="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",Nka(this,a.capabilities||""),Oka(this,a.experiments||""),this.l=a.remoteControllerUrl||"",
this.g=a.localChannelEncryptionKey||"")},Nka=function(a,b){a.capabilities.clear();
(0,g.fe)(b.split(","),g.La(Dka,Pka)).forEach(function(b){a.capabilities.add(b)})},Oka=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},F4=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},G4=function(a,b){return!!b&&(a.id==b||a.uuid==b)},H4=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},Qka=function(a){return new F4(a)},I4=function(a){return g.Ca(a)?(0,g.E)(a,Qka):[]},J4=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},K4=function(a){return g.Ca(a)?"["+(0,g.E)(a,J4).join(",")+"]":"null"},L4=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},Rka=function(a){return(0,g.E)(a,function(a){return{key:a.id,
name:a.name}})},M4=function(a,b){return g.Ra(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},N4=function(a,b){return g.Ra(a,function(a){return G4(a,b)})},Ska=function(){var a=(0,g.yu)();
a&&Kka(a,a.g.Oe(!0))},O4=function(){var a=g.Bu("yt-remote-connected-devices")||[];
g.ob(a);return a},Tka=function(a){if(0==a.length)return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.E)(a,function(a,b){return 0==b?a:a.substring(c.length)})},P4=function(a){g.Au("yt-remote-connected-devices",a,86400)},R4=function(){if(Q4)return Q4;
var a=g.Bu("yt-remote-device-id");a||(a=L4(),g.Au("yt-remote-device-id",a,31536E3));for(var b=O4(),c=1,d=a;g.Va(b,d);)c++,d=a+"#"+c;return Q4=d},S4=function(){var a=O4(),b=R4();
g.Va(a,b);g.Du()&&g.tb(a,b);a=Tka(a);if(0==a.length)try{g.ju("remote_sid")}catch(c){}else try{g.iu("remote_sid",a.join(","),-1)}catch(c){}},T4=function(){return g.Bu("yt-remote-session-browser-channel")},U4=function(){return g.Bu("yt-remote-local-screens")||[]},V4=function(){g.Au("yt-remote-lounge-token-expiration",!0,86400)},Uka=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.E)(U4(),function(a){return a.loungeToken}),c=(0,g.E)(a,function(a){return a.loungeToken});
(0,g.oo)(c,function(a){return!g.Va(b,a)})&&V4();
g.Au("yt-remote-local-screens",a,31536E3)},Vka=function(a,b){g.Au("yt-remote-session-browser-channel",a);
g.Au("yt-remote-session-screen-id",b);var c=O4(),d=R4();g.Va(c,d)||c.push(d);P4(c);S4()},W4=function(a){a||(g.Cu("yt-remote-session-screen-id"),g.Cu("yt-remote-session-video-id"));
S4();a=O4();g.Za(a,R4());P4(a)},Y4=function(){if(!X4){var a=g.cr();
a&&(X4=new g.Nq(a))}return X4?!!X4.get("yt-remote-use-staging-server"):!1},Wka=function(){var a=window.document.createElement("a");
g.rd(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Sb(a)},Xka=function(a,b){var c=g.Zd("SCRIPT");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
g.sd(c,g.ve("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},Yka=function(){var a=Wka(),b=window.document.getElementById(a),c=b&&g.Ns(b,"loaded");
c||b&&!c||(b=Xka(a,function(){g.Ns(b,"loaded")||(g.Ms(b,"loaded","true"),g.Gt(a),g.Kr(g.La(Mka,a),0))}))},Z4=function(a){return!!window.document.currentScript&&(-1!=window.document.currentScript.src.indexOf("?"+a)||-1!=window.document.currentScript.src.indexOf("&"+a))},$4=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},b5=function(a){a.length?a5(a.shift(),function(){b5(a)}):c5()},Zka=function(a){return"chrome-extension://"+a+d5},a5=function(a,b,
c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},e5=function(a){return 0<=window.navigator.userAgent.indexOf(a)},c5=function(){var a=$4();
a&&a(!1,"No cast extension found")},f5=function(){if($ka){var a=2,b=$4(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;a5("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",c5,c)}},ala=function(){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
a&&(f5(),a({command:"cast.sender.init"}))},bla=function(){f5();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);b5(["//www.gstatic.com/eureka/clank/"+(a?(0,window.parseInt)(a[1],10):0)+d5,"//www.gstatic.com/eureka/clank"+d5])},g5=function(a,b,c){g.G.call(this);
this.C=null!=c?(0,g.A)(a,c):a;this.Gc=b;this.B=(0,g.A)(this.aB,this);this.g=!1;this.l=0;this.o=this.Aa=null;this.A=[]},h5=function(){},i5=function(a,b,c,d){this.g=a;
this.o=b;this.D=c;this.C=d||1;this.A=45E3;this.ba=new g.cp(this);this.l=new g.Dg;this.l.setInterval(250)},k5=function(a,b,c){a.vh=1;
a.Of=n4(b.clone());a.Rg=c;a.B=!0;j5(a,null)},l5=function(a,b,c,d,e){a.vh=1;
a.Of=n4(b.clone());a.Rg=null;a.B=c;e&&(a.Cx=!1);j5(a,d)},j5=function(a,b){a.Zh=(0,g.D)();
m5(a);a.eg=a.Of.clone();o4(a.eg,"t",a.C);a.Oj=0;a.fc=a.g.pn(a.g.Ej()?b:null);0<a.Sn&&(a.Wl=new g.xm((0,g.A)(a.Ny,a,a.fc),a.Sn));a.ba.da(a.fc,"readystatechange",a.SK);var c=a.wg?g.qc(a.wg):{};a.Rg?(a.Im="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.fc.send(a.eg,a.Im,a.Rg,c)):(a.Im="GET",a.Cx&&!g.Td&&(c.Connection="close"),a.fc.send(a.eg,a.Im,null,c));a.g.de(1)},t5=function(a,b,c){for(var d=!0;!a.pg&&a.Oj<c.length;){var e=dla(a,c);
if(e==n5){4==b&&(a.Pf=4,o5(15),d=!1);break}else if(e==p5){a.Pf=4;o5(16);d=!1;break}else q5(a,e)}4==b&&0==c.length&&(a.Pf=1,o5(17),d=!1);a.he=a.he&&d;d||(r5(a),s5(a))},dla=function(a,b){var c=a.Oj,d=b.indexOf("\n",c);
if(-1==d)return n5;c=Number(b.substring(c,d));if((0,window.isNaN)(c))return p5;d+=1;if(d+c>b.length)return n5;var e=b.substr(d,c);a.Oj=d+c;return e},w5=function(a,b){a.Zh=(0,g.D)();
m5(a);var c=b?window.location.hostname:"";a.eg=a.Of.clone();g.Wo(a.eg,"DOMAIN",c);g.Wo(a.eg,"t",a.C);try{a.ie=new window.ActiveXObject("htmlfile")}catch(n){r5(a);a.Pf=7;o5(22);s5(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in u5)k=u5[l];else if(l in v5)k=u5[l]=v5[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
u5[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}d+="</body></html>";c=g.td(g.Pc("b/12014412"),d);a.ie.open();a.ie.write(g.ld(c));a.ie.close();a.ie.parentWindow.m=(0,g.A)(a.kK,a);a.ie.parentWindow.d=(0,g.A)(a.Iw,a,!0);a.ie.parentWindow.rpcClose=(0,g.A)(a.Iw,a,!1);c=a.ie.createElement("DIV");a.ie.parentWindow.document.body.appendChild(c);d=g.$c(a.eg.toString());d=g.Ib(g.Xc(d));d=g.td(g.Pc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.qd(c,g.ld(d));a.g.de(1)},m5=function(a){a.Cq=(0,g.D)()+
a.A;
x5(a,a.A)},x5=function(a,b){if(null!=a.ni)throw Error("WatchDog timer not null");
a.ni=y5((0,g.A)(a.vK,a),b)},z5=function(a){a.ni&&(g.x.clearTimeout(a.ni),a.ni=null)},s5=function(a){a.g.Ws()||a.pg||a.g.Ll(a)},r5=function(a){z5(a);
g.ff(a.Wl);a.Wl=null;a.l.stop();g.ep(a.ba);if(a.fc){var b=a.fc;a.fc=null;b.abort();b.dispose()}a.ie&&(a.ie=null)},q5=function(a,b){try{a.g.Bw(a,b),a.g.de(4)}catch(c){}},B5=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;A5(a,b,function(e){e?c(!0):g.x.setTimeout(function(){B5(a,b,c,d,f)},f)})}},A5=function(a,b,c){var d=new window.Image;
d.onload=function(){try{C5(d),c(!0)}catch(e){}};
d.onerror=function(){try{C5(d),c(!1)}catch(e){}};
d.onabort=function(){try{C5(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{C5(d),c(!1)}catch(e){}};
g.x.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},C5=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},D5=function(a){this.g=a;
this.l=new h5},F5=function(a){var b=E5(a.g,a.wi,"/mail/images/cleardot.gif");
n4(b);B5(b.toString(),5E3,(0,g.A)(a.wA,a),3,2E3);a.de(1)},H5=function(a){var b=a.g.I;
if(null!=b)o5(5),b?(o5(11),G5(a.g,a,!1)):(o5(12),G5(a.g,a,!0));else if(a.wd=new i5(a,void 0,void 0,void 0),a.wd.wg=a.Qn,b=a.g,b=E5(b,b.Ej()?a.Ti:null,a.Rn),o5(5),!g.Rd||g.Hc(10))o4(b,"TYPE","xmlhttp"),l5(a.wd,b,!1,a.Ti,!1);else{o4(b,"TYPE","html");var c=a.wd;a=!!a.Ti;c.vh=3;c.Of=n4(b.clone());w5(c,a)}},I5=function(a,b,c){this.g=1;
this.l=[];this.A=[];this.B=new h5;this.G=a||null;this.I=null!=b?b:null;this.C=c||!1},ela=function(a,b){this.g=a;
this.map=b;this.context=null},J5=function(a){g.hf.call(this,"statevent",a)},K5=function(a,b){g.hf.call(this,"timingevent",a);
this.size=b},L5=function(a){g.hf.call(this,"serverreachability",a)},P5=function(a){M5(a);
if(3==a.g){var b=a.rj++,c=a.Fk.clone();g.Wo(c,"SID",a.o);g.Wo(c,"RID",b);g.Wo(c,"TYPE","terminate");N5(a,c);b=new i5(a,a.o,b,void 0);b.vh=2;b.Of=n4(c.clone());(new window.Image).src=b.Of;b.Zh=(0,g.D)();m5(b)}O5(a)},R5=function(a){a.JA(1,0);
a.Fk=E5(a,null,a.Pn);Q5(a)},M5=function(a){a.Ff&&(a.Ff.abort(),a.Ff=null);
a.Jb&&(a.Jb.cancel(),a.Jb=null);a.Qe&&(g.x.clearTimeout(a.Qe),a.Qe=null);S5(a);a.hd&&(a.hd.cancel(),a.hd=null);a.Jf&&(g.x.clearTimeout(a.Jf),a.Jf=null)},T5=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.l.push(new ela(a.yG++,b));2!=a.g&&3!=a.g||Q5(a)},Q5=function(a){a.hd||a.Jf||(a.Jf=y5((0,g.A)(a.Gw,a),0),a.oh=0)},W5=function(a,b){if(1==a.g){if(!b){a.rj=Math.floor(1E5*Math.random());
var c=a.rj++,d=new i5(a,"",c,void 0);d.wg=null;var e=U5(a),f=a.Fk.clone();g.Wo(f,"RID",c);g.Wo(f,"CVER","1");N5(a,f);k5(d,f,e);a.hd=d;a.g=2}}else 3==a.g&&(b?V5(a,b):0==a.l.length||a.hd||V5(a))},V5=function(a,b){if(b)if(6<a.qg){a.l=a.A.concat(a.l);
a.A.length=0;var c=a.rj-1;var d=U5(a)}else c=b.D,d=b.Rg;else c=a.rj++,d=U5(a);var e=a.Fk.clone();g.Wo(e,"SID",a.o);g.Wo(e,"RID",c);g.Wo(e,"AID",a.Ch);N5(a,e);c=new i5(a,a.o,c,a.oh+1);c.wg=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.hd=c;k5(c,e,d)},N5=function(a,b){if(a.Fc){var c=a.Fc.Gs();
c&&g.Zb(c,function(a,c){g.Wo(b,c,a)})}},U5=function(a){var b=Math.min(a.l.length,1E3),c=["count="+b];
if(6<a.qg&&0<b){var d=a.l[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.l[e].g,k=a.l[e].map;f=6>=a.qg?e:f-d;try{g.Zb(k,function(a,b){c.push("req"+f+"_"+b+"="+(0,window.encodeURIComponent)(a))})}catch(l){c.push("req"+f+"_type="+(0,window.encodeURIComponent)("_badmap"))}}a.A=a.A.concat(a.l.splice(0,b));
return c.join("&")},X5=function(a){a.Jb||a.Qe||(a.D=1,a.Qe=y5((0,g.A)(a.Fw,a),0),a.ih=0)},Z5=function(a){if(a.Jb||a.Qe||3<=a.ih)return!1;
a.D++;a.Qe=y5((0,g.A)(a.Fw,a),Y5(a,a.ih));a.ih++;return!0},G5=function(a,b,c){a.Hm=c;
a.xe=b.af;a.C||R5(a)},S5=function(a){null!=a.rg&&(g.x.clearTimeout(a.rg),a.rg=null)},Y5=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},a6=function(a,b){if(2==b||9==b){var c=null;
a.Fc&&(c=null);var d=(0,g.A)(a.xL,a);c||(c=new g.Mo("//www.google.com/images/cleardot.gif"),n4(c));A5(c.toString(),1E4,d)}else o5(2);$5(a,b)},$5=function(a,b){a.g=0;
a.Fc&&a.Fc.Hr(b);O5(a);M5(a)},O5=function(a){a.g=0;
a.xe=-1;if(a.Fc)if(0==a.A.length&&0==a.l.length)a.Fc.fn();else{g.db(a.A);var b=g.db(a.l);a.A.length=0;a.l.length=0;a.Fc.fn(b)}},E5=function(a,b,c){var d=g.Xo(c);
if(""!=d.g)b&&g.Oo(d,b+"."+d.g),g.Po(d,d.B);else{var e=window.location;d=Lka(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Fi&&g.Zb(a.Fi,function(a,b){g.Wo(d,b,a)});
g.Wo(d,"VER",a.qg);N5(a,d);return d},y5=function(a,b){if(!g.Ea(a))throw Error("Fn must not be null and must be a function");
return g.x.setTimeout(function(){a()},b)},o5=function(a){b6.dispatchEvent(new J5(b6,a))},c6=function(){},fla=function(a,b){this.action=a;
this.params=b||{}},d6=function(a,b){g.G.call(this);
this.g=new g.L(this.dK,0,this);g.I(this,this.g);this.Gc=5E3;this.l=0;if(g.Ea(a))b&&(a=(0,g.A)(a,b));else if(a&&g.Ea(a.handleEvent))a=(0,g.A)(a.handleEvent,a);else throw Error("Invalid listener argument");this.o=a},e6=function(a,b,c){this.M=a;
this.C=b;this.o=new g.Mq;this.l=new d6(this.ZL,this);this.g=null;this.J=!1;this.B=null;this.I="";this.G=this.A=0;this.D=[];this.O=c||!1},gla=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.Hm,sessionId:a.g.o,arrayId:a.g.Ch}},f6=function(a,b){a.G=b||0;
a.l.stop();a.g&&(3==a.g.g&&W5(a.g),P5(a.g));a.G=0},g6=function(a){return!!a.g&&3==a.g.g},hla=function(a,b){(a.C.loungeIdToken=b)||a.l.stop()},h6=function(a){this.port=this.domain="";
this.g="/api/lounge";this.l=!0;a=a||window.document.location.href;var b=g.Zg(a)||"";b&&(this.port=":"+b);this.domain=g.Yg(a)||"";a=g.Xb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Rb(a,"10.0")&&(this.l=!1))},i6=function(a,b){var c=a.g;
if(g.t(void 0)?0:a.l)c="https://"+a.domain+a.port+a.g;return g.hh(c+b,{})},j6=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.La(a.A,d,!0),onError:g.La(a.o,e),Zc:g.La(a.B,e)};c&&(a.fb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.as(b,a)},ila=function(){var a=k6;
l6();m6.push(a);n6(m6)},o6=function(a,b){l6();
var c=m6,d=jla(a,String(b));0==c.length?kla(d):(n6(c),(0,g.C)(c,function(a){a(d)}))},l6=function(){m6||(m6=g.z("yt.mdx.remote.debug.handlers_")||[],g.y("yt.mdx.remote.debug.handlers_",m6,void 0))},kla=function(a){var b=(p6+1)%50;
p6=b;q6[b]=a;r6||(r6=49==b)},n6=function(a){var b=q6;
if(b[0]){var c=p6,d=r6?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.C)(a,function(a){a(e)})}while(d!=c);
q6=Array(50);p6=-1;r6=!1}},jla=function(a,b){var c=((0,g.D)()-lla)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},s6=function(a){g.O.call(this);
this.D=a;this.g=[]},t6=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},mla=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.fe)(a.g,function(a){return!!M4(b,a)});
for(var d=0,e=b.length;d<e;d++)c=t6(a,b[d])||c;return c},nla=function(a,b){var c=a.g.length;
a.g=(0,g.fe)(a.g,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.g.length<c},u6=function(a,b,c,d){g.O.call(this);
this.C=a;this.B=b;this.o=c;this.A=d;this.l=0;this.g=null;this.Aa=window.NaN},w6=function(a){s6.call(this,"LocalScreenService");
this.o=a;this.l=window.NaN;v6(this);this.info("Initializing with "+K4(this.g))},x6=function(a){if(a.g.length){var b=(0,g.E)(a.g,function(a){return a.id}),c=i6(a.o,"/pairing/get_lounge_token_batch");
j6(a.o,c,{screen_ids:b.join(",")},(0,g.A)(a.lB,a),(0,g.A)(a.kB,a))}},v6=function(a){var b=I4(U4());
b=(0,g.fe)(b,function(a){return!a.uuid});
return mla(a,b)},y6=function(a,b){Uka((0,g.E)(a.g,H4));
b&&V4()},A6=function(a,b){g.O.call(this);
this.C=b;var c=g.Bu("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.C(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Va(c,l)}this.g=d;this.B=a;this.o=this.A=window.NaN;this.l=null;z6("Initialized with "+g.Og(this.g))},B6=function(a,b,c){var d=i6(a.B,"/pairing/get_screen_availability");
j6(a.B,d,{lounge_token:b.token},(0,g.A)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.A)(function(){c(!1)},a))},C6=function(a,b){a:if(g.cc(b)!=g.cc(a.g))var c=!1;
else{c=g.fc(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(z6("Updated online screens: "+g.Og(a.g)),a.g=b,a.P("screenChange"));ola(a)},D6=function(a){(0,window.isNaN)(a.o)||g.Mr(a.o);
a.o=g.Kr((0,g.A)(a.Xp,a),0<a.A&&a.A<(0,g.D)()?2E4:1E4)},z6=function(a){o6("OnlineScreenService",a)},E6=function(a){var b={};
(0,g.C)(a.C(),function(a){a.token?b[a.token]=a.id:this.zb("Requesting availability of screen w/o lounge token.")});
return b},ola=function(a){a=g.fc(g.$b(a.g,function(a){return a}));
g.ob(a);a.length?g.Au("yt-remote-online-screen-ids",a.join(","),60):g.Cu("yt-remote-online-screen-ids")},F6=function(a){s6.call(this,"ScreenService");
this.C=a;this.l=this.o=null;this.A=[];this.B={};pla(this)},H6=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var k=a.pd();if(k=(c?N4(k,c):null)||N4(k,b)){k.uuid=b;var l=G6(a,k);B6(a.l,l,function(a){e(a?l:null)})}else c?qla(a,c,(0,g.A)(function(a){var f=G6(this,new F4({name:d,
screenId:c,loungeToken:a,dialId:b||""}));B6(this.l,f,function(a){e(a?f:null)})},a),f):e(null)},I6=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},qla=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={fb:{screen_ids:b},method:"POST",context:a,onSuccess:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.as(i6(a.C,"/pairing/get_lounge_token_batch"),e)},J6=function(a){a.g=a.o.pd();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+K4(a.g))},pla=function(a){K6(a);
a.o=new w6(a.C);a.o.subscribe("screenChange",(0,g.A)(a.xB,a));J6(a);a.A=I4(g.Bu("yt-remote-automatic-screen-cache")||[]);K6(a);a.info("Initializing automatic screens: "+K4(a.A));a.l=new A6(a.C,(0,g.A)(a.pd,a,!0));a.l.subscribe("screenChange",(0,g.A)(function(){this.P("onlineScreenChange")},a))},G6=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=N4(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.Au("yt-remote-automatic-screen-cache",(0,g.E)(a.A,H4)));K6(a);a.B[b.uuid]=b.id;g.Au("yt-remote-device-id-map",a.B,31536E3);return b},K6=function(a){a.B=g.Bu("yt-remote-device-id-map")||{}},L6=function(a,b,c){g.O.call(this);
this.O=c;this.I=a;this.l=b;this.o=null},M6=function(a,b){o6(a.O,b)},O6=function(a,b){L6.call(this,a,b,"CastSession");
this.g=null;this.A=0;this.C=(0,g.A)(this.fM,this);this.B=(0,g.A)(this.GK,this);this.A=g.Kr((0,g.A)(function(){N6(this,null)},this),12E4)},rla=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Og(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.za,(0,g.A)(function(){M6(this,"Failed to send message: getMdxSessionStatus.")},a)):M6(a,"Sending yt message without session: "+g.Og(b))},N6=function(a,b){g.Mr(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.o||a.o.id!=b){var c=(0,g.A)(a.Ml,a),d=(0,g.A)(a.ud,a);a.Ps(b,c,d,5)}}else a.ud(Error("Waiting for session status timed out."))},P6=function(a,b,c){L6.call(this,a,b,"DialSession");
this.A=this.G=null;this.J="";this.R=c;this.B=null;this.D=g.za;this.C=window.NaN;this.M=(0,g.A)(this.iM,this);this.g=g.za},Q6=function(a){a.g=a.I.Uy(a.J,a.l.label,a.l.friendlyName,(0,g.A)(function(a){this.g=g.za;
this.Ml(a)},a),(0,g.A)(function(a){this.g=g.za;
this.ud(a)},a))},R6=function(a){var b={};
b.pairingCode=a.J;b.theme=a.R;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}Y4()&&(b.env_useStageMdx=1);return g.fh(b)},S6=function(a,b){L6.call(this,a,b,"ManualSession");
this.g=g.Kr((0,g.A)(this.Dh,this,null),150)},T6=function(a,b,c,d){g.O.call(this);
this.l=a;this.D=b||"233637DE";this.C=c||"cl";this.G=d||!1;this.g=null;this.B=!1;this.o=[];this.A=(0,g.A)(this.qJ,this)},U6=function(a,b){return b?g.Ra(a.o,function(a){return G4(b,a.label)},a):null},V6=function(a){o6("Controller",a)},k6=function(a){window.chrome&&window.chrome.cast&&window.chrome.cast.logMessage&&window.chrome.cast.logMessage(a)},W6=function(a){return a.B||!!a.o.length||!!a.g},X6=function(a,b,c){b!=a.g&&(g.ff(a.g),(a.g=b)?(c?a.P("yt-remote-cast2-receiver-resumed",b.l):a.P("yt-remote-cast2-receiver-selected",
b.l),b.subscribe("sessionScreen",(0,g.A)(a.Ew,a,b)),b.o?a.P("yt-remote-cast2-session-change",b.o):c&&a.g.Dh(null)):a.P("yt-remote-cast2-session-change",null))},Y6=function(a){var b=a.l.Ty(),c=a.g&&a.g.l;
a=(0,g.E)(b,function(a){c&&G4(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=U6(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new window.chrome.cast.Receiver(b,a.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=window.chrome.cast.ReceiverType.CUSTOM&&(c=new window.chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=window.chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},vla=function(a,b,c,d,e,f,k){sla()?tla(b,e,f,k)&&($6(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?a7(a,c):(window.__onGCastApiAvailable=function(b,d){b?a7(a,c):(b7("Failed to load cast API: "+d),c7(!1),$6(!1),g.Cu("yt-remote-cast-available"),g.Cu("yt-remote-cast-receiver"),d7(),c(!1))},
d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):Yka():e5("CriOS")?ala():e5("Android")&&e5("Chrome/")&&window.navigator.presentation?bla():window.chrome&&window.navigator.presentation&&!e5("Edge")?(f5(),b5(ula.map(Zka))):c5())):Z6("Cannot initialize because not running Chrome")},d7=function(){Z6("dispose");
var a=e7();a&&a.dispose();g.y("yt.mdx.remote.cloudview.instance_",null,void 0);f7(!1);g.Et(g7);g7.length=0},h7=function(){return!!g.Bu("yt-remote-cast-installed")},i7=function(){var a=g.Bu("yt-remote-cast-receiver");
return a?a.friendlyName:null},j7=function(){Z6("clearCurrentReceiver");
g.Cu("yt-remote-cast-receiver")},k7=function(){return h7()?e7()?e7().getCastSession():(b7("getCastSelector: Cast is not initialized."),null):(b7("getCastSelector: Cast API is not installed!"),null)},m7=function(){h7()?e7()?l7()?(Z6("Requesting cast selector."),e7().requestSession()):(Z6("Wait for cast API to be ready to request the session."),g7.push(g.Dt("yt-remote-cast2-api-ready",m7))):b7("requestCastSelector: Cast is not initialized."):b7("requestCastSelector: Cast API is not installed!")},n7=
function(a,b){l7()?e7().setConnectedScreenStatus(a,b):b7("setConnectedScreenStatus called before ready.")},sla=function(){var a=0<=g.Xb.search(/ (CrMo|Chrome|CriOS)\//);
return g.nw||a},wla=function(a,b){e7().init(a,b)},tla=function(a,b,c,d){var e=!1;
e7()||(a=new T6(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.Au("yt-remote-cast-available",a);g.Ht("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){Z6("onReceiverSelected: "+a.friendlyName);
g.Au("yt-remote-cast-receiver",a);g.Ht("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){Z6("onReceiverResumed: "+a.friendlyName);
g.Au("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){Z6("onSessionChange: "+J4(a));
a||g.Cu("yt-remote-cast-receiver");g.Ht("yt-remote-cast2-session-change",a)}),g.y("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
Z6("cloudview.createSingleton_: "+e);return e},e7=function(){return g.z("yt.mdx.remote.cloudview.instance_")},a7=function(a,b){c7(!0);
$6(!1);wla(a,function(a){a?(f7(!0),g.Gt("yt-remote-cast2-api-ready")):(b7("Failed to initialize cast API."),c7(!1),g.Cu("yt-remote-cast-available"),g.Cu("yt-remote-cast-receiver"),d7());b(a)})},Z6=function(a){o6("cloudview",a)},b7=function(a){o6("cloudview",a)},c7=function(a){Z6("setCastInstalled_ "+a);
g.Au("yt-remote-cast-installed",a)},l7=function(){return!!g.z("yt.mdx.remote.cloudview.apiReady_")},f7=function(a){Z6("setApiReady_ "+a);
g.y("yt.mdx.remote.cloudview.apiReady_",a,void 0)},$6=function(a){g.y("yt.mdx.remote.cloudview.initializing_",a,void 0)},o7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.g=-1;this.muted=!1;this.audioTrackId=null;this.D=this.G=0;this.l=null;this.hasNext=this.ze=!1;this.J=this.I=this.o=this.B=0;this.A=window.NaN;this.C=!1;this.reset(a)},p7=function(a){a.audioTrackId=null;
a.l=null;a.g=-1;a.ze=!1;a.hasNext=!1;a.G=0;a.D=(0,g.D)();a.B=0;a.o=0;a.I=0;a.J=0;a.A=window.NaN;a.C=!1},q7=function(a){return 1==a.g?((0,g.D)()-a.D)/1E3:0},r7=function(a,b){a.G=b;
a.D=(0,g.D)()},s7=function(a){switch(a.g){case 1:case 1081:return((0,g.D)()-a.D)/1E3+a.G;
case -1E3:return 0}return a.G},t7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&p7(a)},u7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.g;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.rc(a.l);b.hasPrevious=a.ze;b.hasNext=a.hasNext;b.playerTime=a.G;b.playerTimeAt=a.D;b.seekableStart=a.B;b.seekableEnd=a.o;b.duration=a.I;b.loadedTime=a.J;b.liveIngestionTime=a.A;return b},x7=function(a,b){g.O.call(this);
this.g=0;this.A=a;this.C=[];this.B=new C4;this.o=this.l=null;this.I=(0,g.A)(this.hH,this);this.D=(0,g.A)(this.tj,this);this.G=(0,g.A)(this.gH,this);this.J=(0,g.A)(this.tH,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Eq,this),v7(this))):c=3;0!=c&&(b?this.Eq(c):g.Kr((0,g.A)(function(){this.Eq(c)},this),0));
var d=k7();d&&w7(this,d);this.subscribe("yt-remote-cast2-session-change",this.J)},y7=function(a){return new o7(a.A.getPlayerContextData())},v7=function(a){(0,g.C)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.C.push(this.A.subscribe(a,g.La(this.mJ,a),this))},a)},z7=function(a){(0,g.C)(a.C,function(a){this.A.unsubscribeByKey(a)},a);
a.C.length=0},A7=function(a,b){var c=a.B;
50>c.g.length+c.l.length&&a.B.l.push(b)},C7=function(a,b,c){var d=y7(a);
r7(d,c);-1E3!=d.g&&(d.g=b);B7(a,d)},D7=function(a,b,c){a.A.sendMessage(b,c)},B7=function(a,b){z7(a);
a.A.setPlayerContextData(u7(b));v7(a)},w7=function(a,b){a.o&&(a.o.removeUpdateListener(a.I),a.o.removeMediaListener(a.D),a.tj(null));
a.o=b;a.o&&(o6("CP","Setting cast session: "+a.o.sessionId),a.o.addUpdateListener(a.I),a.o.addMediaListener(a.D),a.o.media.length&&a.tj(a.o.media[0]))},E7=function(a){var b=a.l.media,c=a.l.customData;
if(b&&c){var d=y7(a);b.contentId!=d.videoId&&o6("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;r7(d,a.l.getEstimatedTime());B7(a,d)}else o6("CP","No cast media video. Ignoring state update.")},F7=function(a,b,c){return(0,g.A)(function(a){this.zb("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.zb("Retrying "+b+" using MDx browser channel."),D7(this,b,c))},a)},G7=function(a,b,c){g.O.call(this);
this.B=window.NaN;this.R=!1;this.J=this.I=this.M=this.O=window.NaN;this.T=[];this.A=this.D=this.o=this.La=this.g=null;this.pa=a;this.T.push(g.at(window,"beforeunload",(0,g.A)(this.eB,this)));this.l=[];this.La=new o7;this.Y=b.id;this.g=xla(this,c);this.g.subscribe("handlerOpened",this.lH,this);this.g.subscribe("handlerClosed",this.iH,this);this.g.subscribe("handlerError",this.jH,this);this.g.subscribe("handlerMessage",this.kH,this);hla(this.g,b.token);this.subscribe("remoteQueueChange",function(){var a=
this.La.videoId;g.Du()&&g.Au("yt-remote-session-video-id",a)},this)},H7=function(a){o6("conn",a)},xla=function(a,b){return new e6(i6(a.pa,"/bc"),b)},I7=function(a,b){a.P("proxyStateChange",b)},yla=function(a){a.B=g.Kr((0,g.A)(function(){H7("Connecting timeout");
this.C(1)},a),2E4)},J7=function(a){g.Mr(a.B);
a.B=window.NaN},K7=function(a){g.Mr(a.O);
a.O=window.NaN},zla=function(a){L7(a);
a.M=g.Kr((0,g.A)(function(){M7(this,"getNowPlaying")},a),2E4)},L7=function(a){g.Mr(a.M);
a.M=window.NaN},O7=function(a,b){b&&(J7(a),K7(a));
b==(g6(a.g)&&(0,window.isNaN)(a.B))?b&&(I7(a,1),M7(a,"getSubtitlesTrack")):b?(a.Z()&&a.La.reset(),I7(a,1),M7(a,"getNowPlaying"),N7(a)):a.C(1)},Ala=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.La.videoId&&(g.lc(b.params)?a.La.l=null:a.La.l=b.params,a.P("remotePlayerChange"))},P7=function(a,b){var c=b.params.videoId||b.params.video_id,d=(0,window.parseInt)(b.params.currentIndex,10);
a.La.listId=b.params.listId||a.La.listId;t7(a.La,c,d);a.P("remoteQueueChange")},Bla=function(a,b){b.params=b.params||{};
P7(a,b);Q7(a,b);a.P("autoplayDismissed")},Q7=function(a,b){var c=(0,window.parseInt)(b.params.currentTime||b.params.current_time,10);
r7(a.La,(0,window.isNaN)(c)?0:c);c=(0,window.parseInt)(b.params.state,10);c=(0,window.isNaN)(c)?-1:c;-1==c&&-1E3==a.La.g&&(c=-1E3);a.La.g=c;c=Number(b.params.loadedTime);a.La.J=(0,window.isNaN)(c)?0:c;c=Number(b.params.duration);a.La.I=(0,window.isNaN)(c)?0:c;c=a.La;var d=Number(b.params.liveIngestionTime);c.A=d;c.C=(0,window.isNaN)(d)?!1:!0;c=a.La;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.B=(0,window.isNaN)(d)?0:d;c.o=(0,window.isNaN)(e)?0:e;1==a.La.g?zla(a):L7(a);
a.P("remotePlayerChange")},Cla=function(a,b){if(-1E3!=a.La.g){var c=1085;
switch((0,window.parseInt)(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.La.g=c;c=(0,window.parseInt)(b.params.currentTime,10);r7(a.La,(0,window.isNaN)(c)?0:c);a.P("remotePlayerChange")}},Dla=function(a,b){var c="true"==b.params.muted;
a.La.volume=(0,window.parseInt)(b.params.volume,10);a.La.muted=c;a.P("remotePlayerChange")},Ela=function(a,b){a.D=b.params.videoId;
a.P("nowAutoplaying",(0,window.parseInt)(b.params.timeout,10))},Fla=function(a,b){var c="true"==b.params.hasNext;
a.La.ze="true"==b.params.hasPrevious;a.La.hasNext=c;a.P("previousNextChange")},N7=function(a){g.Mr(a.J);
a.J=g.Kr((0,g.A)(a.C,a,1),864E5)},M7=function(a,b,c){c?H7("Sending: action="+b+", params="+g.Og(c)):H7("Sending: action="+b);
a.g.sendMessage(b,c)},R7=function(a){s6.call(this,"ScreenServiceProxy");
this.zc=a;this.l=[];this.l.push(this.zc.$_s("screenChange",(0,g.A)(this.dM,this)));this.l.push(this.zc.$_s("onlineScreenChange",(0,g.A)(this.SI,this)))},Kla=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.Fr("MDX_CONFIG")||b;Ska();S4();S7||(S7=new h6(b?b.loungeApiHost:void 0),Y4()&&(S7.g="/api/loungedev"));T7||(T7=g.z("yt.mdx.remote.deferredProxies_")||[],g.y("yt.mdx.remote.deferredProxies_",T7,void 0));Gla();var c=U7();if(!c){var d=new F6(S7);g.y("yt.mdx.remote.screenService_",d,void 0);c=U7();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);vla(a,d,function(a){a?V7()&&n7(V7(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){g.Ht("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.z("yt.mdx.remote.initialized_")&&(g.y("yt.mdx.remote.initialized_",!0,void 0),W7("Initializing: "+g.Og(b)),X7.push(g.Dt("yt-remote-cast2-availability-change",function(){g.Ht("yt-remote-receiver-availability-change")})),X7.push(g.Dt("yt-remote-cast2-receiver-selected",function(){Y7(null);
g.Ht("yt-remote-auto-connect","cast-selector-receiver")})),X7.push(g.Dt("yt-remote-cast2-receiver-resumed",function(){g.Ht("yt-remote-receiver-resumed","cast-selector-receiver")})),X7.push(g.Dt("yt-remote-cast2-session-change",Hla)),X7.push(g.Dt("yt-remote-connection-change",function(a){a?n7(V7(),"YouTube TV"):Z7()||(n7(null,null),j7())})),a=$7(),b.isAuto&&(a.id+="#dial"),g.wt("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),W7(" -- with channel params: "+
g.Og(a)),Ila(a),c.start(),V7()||Jla())},Lla=function(){var a=a8();
h7()&&g.Bu("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},a8=function(){var a=U7().zc.$_gos();
var b=b8();b&&c8()&&(M4(a,b)||a.push(b));return Rka(a)},d8=function(){var a=Mla();
!a&&h7()&&i7()&&(a={key:"cast-selector-receiver",name:i7()});return a},Mla=function(){var a=a8(),b=b8();
b||(b=Z7());return g.Ra(a,function(a){return b&&G4(b,a.key)?!0:!1})},b8=function(){var a=V7();
if(!a)return null;var b=U7().pd();return N4(b,a)},Hla=function(a){W7("remote.onCastSessionChange_: "+J4(a));
if(a){var b=b8();b&&b.id==a.id?n7(b.id,"YouTube TV"):(b&&e8(),f8(a,1))}else c8()&&e8()},e8=function(){l7()?e7().stopSession():b7("stopSession called before API ready.");
var a=c8();a&&(a.disconnect(1),g8(null))},h8=function(){var a=c8();
return!!a&&3!=a.getProxyState()},W7=function(a){o6("remote",a)},U7=function(){if(!i8){var a=g.z("yt.mdx.remote.screenService_");
i8=a?new R7(a):null}return i8},V7=function(){return g.z("yt.mdx.remote.currentScreenId_")},j8=function(a){g.y("yt.mdx.remote.currentScreenId_",a,void 0)},k8=function(){return g.z("yt.mdx.remote.connectData_")},Y7=function(a){g.y("yt.mdx.remote.connectData_",a,void 0)},c8=function(){return g.z("yt.mdx.remote.connection_")},g8=function(a){var b=c8();
Y7(null);a||j8("");g.y("yt.mdx.remote.connection_",a,void 0);T7&&((0,g.C)(T7,function(b){b(a)}),T7.length=0);
b&&!a?g.Ht("yt-remote-connection-change",!1):!b&&a&&g.Ht("yt-remote-connection-change",!0)},Z7=function(){var a=g.Du();
if(!a)return null;var b=U7().pd();return N4(b,a)},f8=function(a,b){b8()&&b8();
j8(a.id);var c=new G7(S7,a,$7());c.connect(b,k8());c.subscribe("beforeDisconnect",function(a){g.Ht("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){c8()&&g8(null)});
g8(c)},Jla=function(){var a=Z7();
a?(W7("Resume connection to: "+J4(a)),f8(a,0)):(W4(),j7(),W7("Skipping connecting because no session screen found."))},Gla=function(){var a=$7();
if(g.lc(a)){a=R4();var b=g.Bu("yt-remote-session-name")||"",c=g.Bu("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.y("yt.mdx.remote.channelParams_",a,void 0)}},$7=function(){return g.z("yt.mdx.remote.channelParams_")||{}},Ila=function(a){a?(g.Au("yt-remote-session-app",a.app),g.Au("yt-remote-session-name",a.name)):(g.Cu("yt-remote-session-app"),g.Cu("yt-remote-session-name"));
g.y("yt.mdx.remote.channelParams_",a,void 0)},l8=function(a,b,c){g.G.call(this);
this.G=a;this.l=b;this.o=new g.nt(this);g.I(this,this.o);this.o.L(b,"onCaptionsTrackListChanged",this.iI);this.o.L(b,"captionschanged",this.fH);this.o.L(b,"captionssettingschanged",this.fy);this.o.L(b,"videoplayerreset",this.Nl);this.o.L(b,"mdxautoplaycancel",this.vA);this.T=this.o.L(b,"onVolumeChange",this.pw);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.Aw,this);c.subscribe("remotePlayerChange",this.uj,this);c.subscribe("remoteQueueChange",this.Nl,this);c.subscribe("autoplayUpNext",this.aw,
this);c.subscribe("previousNextChange",this.xw,this);c.subscribe("nowAutoplaying",this.rw,this);c.subscribe("autoplayDismissed",this.Zv,this);this.suggestion=null;this.I=new g.hD(64);this.A=new g.L(this.ay,500,this);g.I(this,this.A);this.B=new g.L(this.by,1E3,this);g.I(this,this.B);this.M=new g5(this.KL,0,this);g.I(this,this.M);this.C={};this.O=new g.L(this.Fy,1E3,this);g.I(this,this.O);this.J=new g.xm(this.TE,1E3,this);g.I(this,this.J);this.R=g.za;this.fy();this.Nl();this.uj()},m8=function(a,b){var c=
a.G,d=a.l.getVideoData().lengthSeconds;
c.I=b||0;c.g.P("progresssync",b,d)},o8=function(a){m8(a,0);
a.A.stop();n8(a,new g.hD(64))},q8=function(a,b){if(p8(a)&&!a.D){var c=null;
b&&(c={style:a.l.Ng()},g.tc(c,b));a.g.Px(a.l.getVideoData(1).videoId,c);a.C=y7(a.g).l}},r8=function(a,b){var c=a.l.De();
if(c){var d=c.Pa;var e=c.listId.toString()}var f=a.l.getVideoData(1);c=a.g;var k=f.videoId,l=d;d=f.playerParams;var m=f.yh;f=B4(f);var n=y7(c);l=l||0;var q={videoId:k,currentIndex:l};t7(n,k,l);g.t(b)&&(r7(n,b),q.currentTime=b);g.t(e)&&(q.listId=e);null!=d&&(q.playerParams=d);null!=m&&(q.clickTrackingParams=m);null!=f&&(q.locationInfo=g.Og(f));D7(c,"setPlaylist",q);e||B7(c,n);n8(a,new g.hD(1))},s8=function(a,b){if(b){var c=a.l.Nb("captions","tracklist",{Dt:1});
c&&c.length?(a.l.Xc("captions","track",b),a.D=!1):(a.l.Lh("captions"),a.D=!0)}else a.l.Xc("captions","track",{})},p8=function(a){return y7(a.g).videoId==a.l.getVideoData(1).videoId},n8=function(a,b){a.B.stop();
var c=a.I;if(!g.mD(c,b)){var d=g.U(b,2);d!=g.U(a.I,2)&&g.SJ(a.l,d);a.I=b;t8(a.G,c,b)}},v8=function(a){g.R.call(this,{F:"div",
H:"ytp-remote",K:[{F:"div",H:"ytp-remote-display-status",K:[{F:"div",H:"ytp-remote-display-status-icon",K:[g.kO()]},{F:"div",H:"ytp-remote-display-status-text",V:"{{statustext}}"}]}]});this.l=new g.bP(this,250);g.I(this,this.l);this.o=a;this.L(a,"presentingplayerstatechange",this.A);u8(this,g.PJ(a))},u8=function(a,b){if(3==a.o.Ca()){var c={RECEIVER_NAME:a.o.Nb("remote","currentReceiver").name};
c=g.U(b,128)?g.sW("Error on $RECEIVER_NAME",c):g.nD(b)||g.U(b,4)?g.sW("Playing on $RECEIVER_NAME",c):g.sW("Connected to $RECEIVER_NAME",c);a.updateValue("statustext",c);a.l.show()}else a.l.hide()},w8=function(a,b){g.CT.call(this,"Play on",0,a,b);
this.l=a;this.G={};this.L(a,"onMdxReceiversChange",this.J);this.L(a,"presentingplayerstatechange",this.J);this.J()},x8=function(a){g.zK.call(this,a);
this.o={key:L4(),name:"This computer"};this.B=null;this.C=[];this.J=this.l=null;this.G=[this.o];this.A=this.o;this.D=new g.hD(64);this.I=0;if(!g.qA(g.V(this.g))){a=this.g;var b=g.rv(a);b&&(b=b.ll())&&(b=new w8(a,b),g.I(this,b));b=new v8(a);g.I(this,b);g.lK(a,b.element,4)}},t8=function(a,b,c){a.D=c;
a.g.P("presentingplayerstatechange",new g.sD(c,b))},y8=function(a,b){if(b.key!=a.A.key)if(b.key==a.o.key)e8();
else{a.A=b;var c=a.g.getPlaylistId();var d=a.g.getVideoData(1);var e=d.videoId;if(c||e){var f=a.g.De();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.sb(l).videoId}else k=[e];f=a.g.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.yh,index:Math.max(a.g.Bu(),0),currentTime:0==f?void 0:f};(d=B4(d))&&(c.locationInfo=d);d=c}else d=null;W7("Connecting to: "+g.Og(b));"cast-selector-receiver"==b.key?(Y7(d||null),l7()?e7().setLaunchParams(d||null):
b7("setLaunchParams called before ready.")):!d&&h8()&&V7()==b.key?g.Ht("yt-remote-connection-change",!0):(e8(),Y7(d||null),d=U7().pd(),(d=N4(d,b.key))&&f8(d,1))}},Ika=/^https?$/i,Nla=["POST",
"PUT"];g.B(z4,g.Lf);g.h=z4.prototype;
g.h.send=function(a,b,c,d){if(this.g)throw Error("[goog.net.XhrIo] Object is active with another request="+this.I+"; newUri="+a);b=b?b.toUpperCase():"GET";this.I=a;this.B="";this.A=0;this.X=b;this.T=!1;this.l=!0;this.g=this.R?r4(this.R):r4(g.UW);this.O=this.R?q4(this.R):q4(g.UW);this.g.onreadystatechange=(0,g.A)(this.Ys,this);try{m4(s4(this,"Opening Xhr")),this.Y=!0,this.g.open(b,String(a),!0),this.Y=!1}catch(f){m4(s4(this,"Error opening Xhr: "+f.message));w4(this,f);return}a=c||"";var e=this.headers.clone();
d&&Fka(d,function(a,b){e.set(b,a)});
d=g.Ra(e.nd(),Gka);c=g.x.FormData&&a instanceof g.x.FormData;!g.Va(Nla,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(a,b){this.g.setRequestHeader(b,a)},this);
this.fa&&(this.g.responseType=this.fa);"withCredentials"in this.g&&this.g.withCredentials!==this.Z&&(this.g.withCredentials=this.Z);try{t4(this),0<this.C&&(this.M=Hka(this.g),m4(s4(this,"Will abort after "+this.C+"ms if incomplete, xhr2 "+this.M)),this.M?(this.g.timeout=this.C,this.g.ontimeout=(0,g.A)(this.Zs,this)):this.D=g.Eg(this.Zs,this.C,this)),m4(s4(this,"Sending request")),this.G=!0,this.g.send(a),this.G=!1}catch(f){m4(s4(this,"Send error: "+f.message)),w4(this,f)}};
g.h.Zs=function(){"undefined"!=typeof g.wW&&this.g&&(this.B="Timed out after "+this.C+"ms, aborting",this.A=8,s4(this,this.B),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.g&&this.l&&(s4(this,"Aborting"),this.l=!1,this.o=!0,this.g.abort(),this.o=!1,this.A=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),v4(this))};
g.h.U=function(){this.g&&(this.l&&(this.l=!1,this.o=!0,this.g.abort(),this.o=!1),v4(this,!0));z4.wa.U.call(this)};
g.h.Ys=function(){this.ha()||(this.Y||this.G||this.o?y4(this):this.pJ())};
g.h.pJ=function(){y4(this)};
g.h.isActive=function(){return!!this.g};
g.h.getStatus=function(){try{return 2<x4(this)?this.g.status:-1}catch(a){return-1}};
var v5={"\x00":"\\0","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},u5={"'":"\\'"},Ola={};g.h=C4.prototype;g.h.isEmpty=function(){return 0==this.g.length&&0==this.l.length};
g.h.clear=function(){this.g=[];this.l=[]};
g.h.contains=function(a){return g.Va(this.g,a)||g.Va(this.l,a)};
g.h.remove=function(a){var b=this.g;var c=(0,g.Dga)(b,a);0<=c?(g.Ya(b,c),b=!0):b=!1;return b||g.Za(this.l,a)};
g.h.sc=function(){for(var a=[],b=this.g.length-1;0<=b;--b)a.push(this.g[b]);var c=this.l.length;for(b=0;b<c;++b)a.push(this.l[b]);return a};
var Pka={sM:"atp",DO:"ska",sO:"que",SN:"mus",CO:"sus",iN:"dsp"};E4.prototype.qk=function(){var a=new E4({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.o=this.o;a.l=this.l;a.g=this.g};
var X4,Q4="",d5=Z4("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",$ka=Z4("loadCastFramework")||Z4("loadCastApplicationFramework"),ula=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.B(g5,g.G);g.h=g5.prototype;g.h.ZA=function(a){this.A=arguments;this.g=!1;this.Aa?this.o=(0,g.D)()+this.Gc:this.Aa=g.Eg(this.B,this.Gc)};
g.h.stop=function(){this.Aa&&(g.x.clearTimeout(this.Aa),this.Aa=null);this.o=null;this.g=!1;this.A=[]};
g.h.pause=function(){++this.l};
g.h.resume=function(){this.l&&(--this.l,!this.l&&this.g&&(this.g=!1,this.C.apply(null,this.A)))};
g.h.U=function(){this.stop();g5.wa.U.call(this)};
g.h.aB=function(){this.o?(this.Aa=g.Eg(this.B,this.o-(0,g.D)()),this.o=null):(this.Aa=null,this.l?this.g=!0:(this.g=!1,this.C.apply(null,this.A)))};h5.prototype.stringify=function(a){return g.x.JSON.stringify(a,void 0)};
h5.prototype.parse=function(a){return g.x.JSON.parse(a,void 0)};g.h=i5.prototype;g.h.wg=null;g.h.he=!1;g.h.ni=null;g.h.Cq=null;g.h.Zh=null;g.h.vh=null;g.h.Of=null;g.h.eg=null;g.h.Rg=null;g.h.fc=null;g.h.Oj=0;g.h.ie=null;g.h.Im=null;g.h.Pf=null;g.h.Ui=-1;g.h.Cx=!0;g.h.pg=!1;g.h.Sn=0;g.h.Wl=null;var p5={},n5={};g.h=i5.prototype;g.h.setTimeout=function(a){this.A=a};
g.h.SK=function(a){a=a.target;var b=this.Wl;b&&3==x4(a)?b.th():this.Ny(a)};
g.h.Ny=function(a){try{if(a==this.fc)a:{var b=x4(this.fc),c=this.fc.A,d=this.fc.getStatus();if(g.Rd&&!g.Hc(10)||g.Td&&!g.Fc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Qh&&!A4(this.fc))break a;this.pg||4!=b||7==c||(8==c||0>=d?this.g.de(3):this.g.de(2));z5(this);var e=this.fc.getStatus();this.Ui=e;var f=A4(this.fc);(this.he=200==e)?(4==b&&r5(this),this.B?(t5(this,b,f),g.Qh&&this.he&&3==b&&(this.ba.da(this.l,"tick",this.OK),this.l.start())):q5(this,f),this.he&&!this.pg&&(4==b?this.g.Ll(this):(this.he=
!1,m5(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.Pf=3,o5(13)):(this.Pf=0,o5(14)),r5(this),s5(this))}}catch(k){this.fc&&A4(this.fc)}finally{}};
g.h.OK=function(){var a=x4(this.fc),b=A4(this.fc);this.Oj<b.length&&(z5(this),t5(this,a,b),this.he&&4!=a&&m5(this))};
g.h.kK=function(a){y5((0,g.A)(this.jK,this,a),0)};
g.h.jK=function(a){this.pg||(z5(this),q5(this,a),m5(this))};
g.h.Iw=function(a){y5((0,g.A)(this.iK,this,a),0)};
g.h.iK=function(a){this.pg||(r5(this),this.he=a,this.g.Ll(this),this.g.de(4))};
g.h.cancel=function(){this.pg=!0;r5(this)};
g.h.vK=function(){this.ni=null;var a=(0,g.D)();0<=a-this.Cq?(2!=this.vh&&this.g.de(3),r5(this),this.Pf=2,o5(18),s5(this)):x5(this,this.Cq-a)};g.h=D5.prototype;g.h.Qn=null;g.h.wd=null;g.h.Xl=!1;g.h.Xs=null;g.h.Bk=null;g.h.uo=null;g.h.Rn=null;g.h.Hd=null;g.h.af=-1;g.h.Ti=null;g.h.wi=null;g.h.connect=function(a){this.Rn=a;a=E5(this.g,null,this.Rn);o5(3);this.Xs=(0,g.D)();var b=this.g.G;null!=b?(this.Ti=b[0],(this.wi=b[1])?(this.Hd=1,F5(this)):(this.Hd=2,H5(this))):(o4(a,"MODE","init"),this.wd=new i5(this,void 0,void 0,void 0),this.wd.wg=this.Qn,l5(this.wd,a,!1,null,!0),this.Hd=0)};
g.h.wA=function(a){if(a)this.Hd=2,H5(this);else{o5(4);var b=this.g;b.xe=b.Ff.af;a6(b,9)}a&&this.de(2)};
g.h.pn=function(a){return this.g.pn(a)};
g.h.abort=function(){this.wd&&(this.wd.cancel(),this.wd=null);this.af=-1};
g.h.Ws=function(){return!1};
g.h.Bw=function(a,b){this.af=a.Ui;if(0==this.Hd)if(b){try{var c=this.l.parse(b)}catch(d){c=this.g;c.xe=this.af;a6(c,2);return}this.Ti=c[0];this.wi=c[1]}else c=this.g,c.xe=this.af,a6(c,2);else if(2==this.Hd)if(this.Xl)o5(7),this.uo=(0,g.D)();else if("11111"==b){if(o5(6),this.Xl=!0,this.Bk=(0,g.D)(),c=this.Bk-this.Xs,!g.Rd||g.Hc(10)||500>c)this.af=200,this.wd.cancel(),o5(12),G5(this.g,this,!0)}else o5(8),this.Bk=this.uo=(0,g.D)(),this.Xl=!1};
g.h.Ll=function(){this.af=this.wd.Ui;if(this.wd.he)0==this.Hd?this.wi?(this.Hd=1,F5(this)):(this.Hd=2,H5(this)):2==this.Hd&&((!g.Rd||g.Hc(10)?!this.Xl:200>this.uo-this.Bk)?(o5(11),G5(this.g,this,!1)):(o5(12),G5(this.g,this,!0)));else{0==this.Hd?o5(9):2==this.Hd&&o5(10);var a=this.g;a.xe=this.af;a6(a,2)}};
g.h.Ej=function(){return this.g.Ej()};
g.h.isActive=function(){return this.g.isActive()};
g.h.de=function(a){this.g.de(a)};g.h=I5.prototype;g.h.Fi=null;g.h.hd=null;g.h.Jb=null;g.h.Pn=null;g.h.Fk=null;g.h.zr=null;g.h.Nk=null;g.h.rj=0;g.h.yG=0;g.h.Fc=null;g.h.Jf=null;g.h.Qe=null;g.h.rg=null;g.h.Ff=null;g.h.Hm=null;g.h.Ch=-1;g.h.Vt=-1;g.h.xe=-1;g.h.oh=0;g.h.ih=0;g.h.qg=8;var b6=new g.Lf;g.B(J5,g.hf);g.B(K5,g.hf);g.B(L5,g.hf);g.h=I5.prototype;g.h.connect=function(a,b,c,d,e){o5(0);this.Pn=b;this.Fi=c||{};d&&g.t(e)&&(this.Fi.OSID=d,this.Fi.OAID=e);this.C?(y5((0,g.A)(this.Ur,this,a),100),R5(this)):this.Ur(a)};
g.h.Ur=function(a){this.Ff=new D5(this);this.Ff.Qn=null;this.Ff.l=this.B;this.Ff.connect(a)};
g.h.Ws=function(){return 0==this.g};
g.h.Gw=function(a){this.Jf=null;W5(this,a)};
g.h.Fw=function(){this.Qe=null;this.Jb=new i5(this,this.o,"rpc",this.D);this.Jb.wg=null;this.Jb.Sn=0;var a=this.zr.clone();g.Wo(a,"RID","rpc");g.Wo(a,"SID",this.o);g.Wo(a,"CI",this.Hm?"0":"1");g.Wo(a,"AID",this.Ch);N5(this,a);if(!g.Rd||g.Hc(10))g.Wo(a,"TYPE","xmlhttp"),l5(this.Jb,a,!0,this.Nk,!1);else{g.Wo(a,"TYPE","html");var b=this.Jb,c=!!this.Nk;b.vh=3;b.Of=n4(a.clone());w5(b,c)}};
g.h.Bw=function(a,b){if(0!=this.g&&(this.Jb==a||this.hd==a))if(this.xe=a.Ui,this.hd==a&&3==this.g)if(7<this.qg){try{var c=this.B.parse(b)}catch(f){c=null}if(g.Ca(c)&&3==c.length)if(0==c[0])a:{if(!this.Qe){if(this.Jb)if(this.Jb.Zh+3E3<this.hd.Zh)S5(this),this.Jb.cancel(),this.Jb=null;else break a;Z5(this);o5(19)}}else this.Vt=c[1],0<this.Vt-this.Ch&&37500>c[2]&&this.Hm&&0==this.ih&&!this.rg&&(this.rg=y5((0,g.A)(this.bH,this),6E3));else a6(this,11)}else b!=Ola.SM.g&&a6(this,11);else if(this.Jb==a&&
S5(this),!g.yb(b)){c=this.B.parse(b);g.Ca(c);for(var d=0;d<c.length;d++){var e=c[d];this.Ch=e[0];e=e[1];2==this.g?"c"==e[0]?(this.o=e[1],this.Nk=e[2],e=e[3],null!=e?this.qg=e:this.qg=6,this.g=3,this.Fc&&this.Fc.Jr(),this.zr=E5(this,this.Ej()?this.Nk:null,this.Pn),X5(this)):"stop"==e[0]&&a6(this,7):3==this.g&&("stop"==e[0]?a6(this,7):"noop"!=e[0]&&this.Fc&&this.Fc.Ir(e),this.ih=0)}}};
g.h.bH=function(){null!=this.rg&&(this.rg=null,this.Jb.cancel(),this.Jb=null,Z5(this),o5(20))};
g.h.Ll=function(a){if(this.Jb==a){S5(this);this.Jb=null;var b=2}else if(this.hd==a)this.hd=null,b=1;else return;this.xe=a.Ui;if(0!=this.g)if(a.he)1==b?(b=(0,g.D)()-a.Zh,b6.dispatchEvent(new K5(b6,a.Rg?a.Rg.length:0,b,this.oh)),Q5(this),this.A.length=0):X5(this);else{var c=a.Pf,d;if(!(d=3==c||7==c||0==c&&0<this.xe)){if(d=1==b)this.hd||this.Jf||1==this.g||2<=this.oh?d=!1:(this.Jf=y5((0,g.A)(this.Gw,this,a),Y5(this,this.oh)),this.oh++,d=!0);d=!(d||2==b&&Z5(this))}if(d)switch(c){case 1:a6(this,5);break;
case 4:a6(this,10);break;case 3:a6(this,6);break;case 7:a6(this,12);break;default:a6(this,2)}}};
g.h.JA=function(a){if(!g.Va(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.xL=function(a){a?o5(2):(o5(1),$5(this,8))};
g.h.pn=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new z4;a.Z=!1;return a};
g.h.isActive=function(){return!!this.Fc&&this.Fc.isActive(this)};
g.h.de=function(a){b6.dispatchEvent(new L5(b6,a))};
g.h.Ej=function(){return!(!g.Rd||g.Hc(10))};
g.h=c6.prototype;g.h.Jr=function(){};
g.h.Ir=function(){};
g.h.Hr=function(){};
g.h.fn=function(){};
g.h.Gs=function(){return{}};
g.h.isActive=function(){return!0};g.B(d6,g.G);g.h=d6.prototype;g.h.dK=function(){this.Gc=Math.min(3E5,2*this.Gc);this.o();this.l&&this.start()};
g.h.start=function(){var a=this.Gc+15E3*Math.random();g.uq(this.g,a);this.l=(0,g.D)()+a};
g.h.stop=function(){this.g.stop();this.l=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.Gc=5E3};g.B(e6,c6);g.h=e6.prototype;g.h.subscribe=function(a,b,c){return this.o.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.o.unsubscribe(a,b,c)};
g.h.Bc=function(a){return this.o.Bc(a)};
g.h.P=function(a,b){return this.o.P.apply(this.o,arguments)};
g.h.dispose=function(){this.J||(this.J=!0,g.ff(this.o),f6(this),g.ff(this.l),this.l=null)};
g.h.ha=function(){return this.J};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.I="";this.l.stop();this.B=a||null;this.A=b||0;a=this.M+"/test";b=this.M+"/bind";var d=new I5(c?c.firstTestResults:null,c?c.secondTestResults:null,this.O),e=this.g;e&&(e.Fc=null);d.Fc=this;this.g=d;e?this.g.connect(a,b,this.C,e.o,e.Ch):c?this.g.connect(a,b,this.C,c.sessionId,c.arrayId):this.g.connect(a,b,this.C)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.tc(c,b);this.l.isActive()||2==(this.g?this.g.g:0)?this.D.push(c):g6(this)&&T5(this.g,c)};
g.h.Jr=function(){this.l.reset();this.B=null;this.A=0;if(this.D.length){var a=this.D;this.D=[];for(var b=0,c=a.length;b<c;++b)T5(this.g,a[b])}this.P("handlerOpened")};
g.h.Hr=function(a){var b=2==a&&401==this.g.xe;4==a||b||this.l.start();this.P("handlerError",a)};
g.h.fn=function(a){if(!this.l.isActive())this.P("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.D.push(d)}};
g.h.Gs=function(){var a={v:2};this.I&&(a.gsessionid=this.I);0!=this.A&&(a.ui=""+this.A);0!=this.G&&(a.ui=""+this.G);this.B&&g.tc(a,this.B);return a};
g.h.Ir=function(a){"S"==a[0]?this.I=a[1]:"gracefulReconnect"==a[0]?(this.l.start(),P5(this.g)):this.P("handlerMessage",new fla(a[0],a[1]))};
g.h.ZL=function(){this.l.isActive();var a=this.g,b=0;a.Jb&&b++;a.hd&&b++;0!=b||this.connect(this.B,this.A)};h6.prototype.A=function(a,b,c,d){b?a(d):a({text:c.responseText})};
h6.prototype.o=function(a,b){a(Error("Request error: "+b.status))};
h6.prototype.B=function(a){a(Error("request timed out"))};var lla=(0,g.D)(),m6=null,q6=Array(50),p6=-1,r6=!1;g.B(s6,g.O);s6.prototype.pd=function(){return this.g};
s6.prototype.contains=function(a){return!!M4(this.g,a)};
s6.prototype.get=function(a){return a?N4(this.g,a):null};
s6.prototype.info=function(a){o6(this.D,a)};g.B(u6,g.O);var z8=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=u6.prototype;g.h.start=function(){!this.g&&(0,window.isNaN)(this.Aa)&&this.Sy()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);(0,window.isNaN)(this.Aa)||(g.Mr(this.Aa),this.Aa=window.NaN)};
g.h.U=function(){this.stop();u6.wa.U.call(this)};
g.h.Sy=function(){this.Aa=window.NaN;this.g=g.as(i6(this.C,"/pairing/get_screen"),{method:"POST",fb:{pairing_code:this.B},timeout:5E3,onSuccess:(0,g.A)(this.bM,this),onError:(0,g.A)(this.aM,this),Zc:(0,g.A)(this.cM,this)})};
g.h.bM=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.o;c.name=this.A;this.P("pairingComplete",new F4(c))};
g.h.aM=function(a){this.g=null;a.status&&404==a.status?this.l>=z8.length?this.P("pairingFailed",Error("DIAL polling timed out")):(a=z8[this.l],this.Aa=g.Kr((0,g.A)(this.Sy,this),a),this.l++):this.P("pairingFailed",Error("Server error "+a.status))};
g.h.cM=function(){this.g=null;this.P("pairingFailed",Error("Server not responding"))};g.B(w6,s6);g.h=w6.prototype;g.h.start=function(){v6(this)&&this.P("screenChange");!g.Bu("yt-remote-lounge-token-expiration")&&x6(this);g.Mr(this.l);this.l=g.Kr((0,g.A)(this.start,this),1E4)};
g.h.add=function(a,b){v6(this);t6(this,a);y6(this,!1);this.P("screenChange");b(a);a.token||x6(this)};
g.h.remove=function(a,b){var c=v6(this);nla(this,a)&&(y6(this,!1),c=!0);b(a);c&&this.P("screenChange")};
g.h.Bm=function(a,b,c,d){var e=v6(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,y6(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.P("screenChange")};
g.h.U=function(){g.Mr(this.l);w6.wa.U.call(this)};
g.h.lB=function(a){v6(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}y6(this,!b);b&&o6(this.D,"Missed "+b+" lounge tokens.")};
g.h.kB=function(a){o6(this.D,"Requesting lounge tokens failed: "+a)};g.B(A6,g.O);g.h=A6.prototype;g.h.start=function(){var a=(0,window.parseInt)(g.Bu("yt-remote-fast-check-period")||"0",10);(this.A=(0,g.D)()-144E5<a?0:a)?D6(this):(this.A=(0,g.D)()+3E5,g.Au("yt-remote-fast-check-period",this.A),this.Xp())};
g.h.isEmpty=function(){return g.lc(this.g)};
g.h.update=function(){z6("Updating availability on schedule.");var a=this.C(),b=g.$b(this.g,function(b,d){return b&&!!N4(a,d)},this);
C6(this,b)};
g.h.U=function(){g.Mr(this.o);this.o=window.NaN;this.l&&(this.l.abort(),this.l=null);A6.wa.U.call(this)};
g.h.Xp=function(){g.Mr(this.o);this.o=window.NaN;this.l&&this.l.abort();var a=E6(this);if(g.cc(a)){var b=i6(this.B,"/pairing/get_screen_availability");this.l=j6(this.B,b,{lounge_token:g.fc(a).join(",")},(0,g.A)(this.KJ,this,a),(0,g.A)(this.JJ,this))}else C6(this,{}),D6(this)};
g.h.KJ=function(a,b){this.l=null;var c=g.fc(E6(this));if(g.rb(c,g.fc(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;C6(this,d);D6(this)}else this.zb("Changing Screen set during request."),this.Xp()};
g.h.JJ=function(a){this.zb("Screen availability failed: "+a);this.l=null;D6(this)};
g.h.zb=function(a){o6("OnlineScreenService",a)};g.B(F6,s6);g.h=F6.prototype;g.h.start=function(){this.o.start();this.l.start();this.g.length&&(this.P("screenChange"),this.l.isEmpty()||this.P("onlineScreenChange"))};
g.h.add=function(a,b,c){this.o.add(a,b,c)};
g.h.remove=function(a,b,c){this.o.remove(a,b,c);this.l.update()};
g.h.Bm=function(a,b,c,d){this.o.contains(a)?this.o.Bm(a,b,c,d):(a="Updating name of unknown screen: "+a.name,o6(this.D,a),d(Error(a)))};
g.h.pd=function(a){return a?this.g:g.cb(this.g,(0,g.fe)(this.A,function(a){return!this.contains(a)},this))};
g.h.Ty=function(){return(0,g.fe)(this.pd(!0),function(a){return!!this.l.g[a.id]},this)};
g.h.Uy=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new u6(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.A)(function(a){g.ff(f);d(G6(this,a))},this));
f.subscribe("pairingFailed",function(a){g.ff(f);e(a)});
f.start();return(0,g.A)(f.stop,f)};
g.h.eM=function(a,b,c,d){g.as(i6(this.C,"/pairing/get_screen"),{method:"POST",fb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.A)(function(a,d){var e=new F4(d.screen||{});if(!e.name||I6(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);I6(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(G6(this,e))},this),
onError:(0,g.A)(function(a){d(Error("pairing request failed: "+a.status))},this),
Zc:(0,g.A)(function(){d(Error("pairing request timed out."))},this)})};
g.h.U=function(){g.ff(this.o);g.ff(this.l);F6.wa.U.call(this)};
g.h.xB=function(){J6(this);this.P("screenChange");this.l.update()};
F6.prototype.dispose=F6.prototype.dispose;g.B(L6,g.O);g.h=L6.prototype;g.h.Ml=function(a){this.o=a;this.P("sessionScreen",this.o)};
g.h.ud=function(a){this.ha()||(a&&M6(this,""+a),this.o=null,this.P("sessionScreen",null))};
g.h.info=function(a){o6(this.O,a)};
g.h.Wy=function(){return null};
g.h.cq=function(a){var b=this.l;a?(b.displayStatus=new window.chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;window.chrome.cast.setReceiverDisplayStatus(b,(0,g.A)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.A)(function(){M6(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.U=function(){this.cq("");L6.wa.U.call(this)};g.B(O6,L6);g.h=O6.prototype;g.h.bq=function(a){if(this.g){if(this.g==a)return;M6(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.C);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.g=a;this.g.addUpdateListener(this.C);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);rla(this)};
g.h.Dh=function(a){this.info("launchWithParams no-op for Cast: "+g.Og(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.A)(function(){this.ud()},this),(0,g.A)(function(){this.ud(Error("Failed to stop receiver app."))},this)):this.ud(Error("Stopping cast device witout session."))};
g.h.cq=g.za;g.h.U=function(){this.info("disposeInternal");g.Mr(this.A);this.A=0;this.g&&(this.g.removeUpdateListener(this.C),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.g=null;O6.wa.U.call(this)};
g.h.GK=function(a,b){if(!this.ha())if(b){var c=g.Fq(b);if(g.Fa(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Og(c));switch(d){case "mdxSessionStatus":N6(this,c.screenId);break;default:M6(this,"Unknown youtube message: "+d)}}else M6(this,"Unable to parse message.")}else M6(this,"No data in message.")};
g.h.Ps=function(a,b,c,d){H6(this.I,this.l.label,a,this.l.friendlyName,(0,g.A)(function(e){e?b(e):0<=d?(M6(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.Kr((0,g.A)(this.Ps,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.Wy=function(){return this.g};
g.h.fM=function(a){this.ha()||a||(M6(this,"Cast session died."),this.ud())};g.B(P6,L6);g.h=P6.prototype;g.h.bq=function(a){this.A=a;this.A.addUpdateListener(this.M)};
g.h.Dh=function(a){this.B=a;this.D()};
g.h.stop=function(){this.g();this.g=g.za;g.Mr(this.C);this.A?this.A.stop((0,g.A)(this.ud,this,null),(0,g.A)(this.ud,this,"Failed to stop DIAL device.")):this.ud()};
g.h.U=function(){this.g();this.g=g.za;g.Mr(this.C);this.A&&this.A.removeUpdateListener(this.M);this.A=null;P6.wa.U.call(this)};
g.h.iM=function(a){this.ha()||a||(M6(this,"DIAL session died."),this.g(),this.g=g.za,this.ud())};
g.h.ho=function(a){this.J=L4();if(this.B){var b=new window.chrome.cast.DialLaunchResponse(!0,R6(this));a(b);Q6(this)}else this.D=(0,g.A)(function(){g.Mr(this.C);this.D=g.za;this.C=window.NaN;var b=new window.chrome.cast.DialLaunchResponse(!0,R6(this));a(b);Q6(this)},this),this.C=g.Kr((0,g.A)(function(){this.D()},this),100)};
g.h.TB=function(a,b,c){H6(this.I,this.G.receiver.label,a,this.l.friendlyName,(0,g.A)(function(a){a&&a.token?(this.Ml(a),b(new window.chrome.cast.DialLaunchResponse(!1))):this.ho(b,c)},this),(0,g.A)(function(a){M6(this,"Failed to get DIAL screen: "+a);
this.ho(b,c)},this))};g.B(S6,L6);S6.prototype.stop=function(){this.ud()};
S6.prototype.bq=g.za;S6.prototype.Dh=function(){g.Mr(this.g);this.g=window.NaN;var a=N4(this.I.pd(),this.l.label);a?this.Ml(a):this.ud(Error("No such screen"))};
S6.prototype.U=function(){g.Mr(this.g);this.g=window.NaN;S6.wa.U.call(this)};g.B(T6,g.O);g.h=T6.prototype;
g.h.init=function(a,b){window.chrome.cast.timeout.requestSession=3E4;var c=new window.chrome.cast.SessionRequest(this.D);this.G||(c.dialRequest=new window.chrome.cast.DialRequest("YouTube"));var d=window.chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?window.chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:window.chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new window.chrome.cast.ApiConfig(c,(0,g.A)(this.Dw,this),(0,g.A)(this.uJ,this),d,e);c.customDialLaunchCallback=(0,g.A)(this.CH,this);window.chrome.cast.initialize(c,
(0,g.A)(function(){this.ha()||(window.chrome.cast.addReceiverActionListener(this.A),ila(),this.l.subscribe("onlineScreenChange",(0,g.A)(this.Vy,this)),this.o=Y6(this),window.chrome.cast.setCustomReceivers(this.o,g.za,(0,g.A)(function(a){this.zb("Failed to set initial custom receivers: "+g.Og(a))},this)),this.P("yt-remote-cast2-availability-change",W6(this)),b(!0))},this),(0,g.A)(function(a){this.zb("Failed to initialize API: "+g.Og(a));
b(!1)},this))};
g.h.nL=function(a,b){V6("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.o;if(!a||c&&c.id!=a)V6("Unsetting old screen status: "+this.g.l.friendlyName),X6(this,null)}if(a&&b){if(!this.g){c=N4(this.l.pd(),a);if(!c){V6("setConnectedScreenStatus: Unknown screen.");return}var d=U6(this,c);d||(V6("setConnectedScreenStatus: Connected receiver not custom..."),d=new window.chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM,this.o.push(d),
window.chrome.cast.setCustomReceivers(this.o,g.za,(0,g.A)(function(a){this.zb("Failed to set initial custom receivers: "+g.Og(a))},this)));
V6("setConnectedScreenStatus: new active receiver: "+d.friendlyName);X6(this,new S6(this.l,d),!0)}this.g.cq(b)}else V6("setConnectedScreenStatus: no screen.")};
g.h.oL=function(a){this.ha()?this.zb("Setting connection data on disposed cast v2"):this.g?this.g.Dh(a):this.zb("Setting connection data without a session")};
g.h.hM=function(){this.ha()?this.zb("Stopping session on disposed cast v2"):this.g?(this.g.stop(),X6(this,null)):V6("Stopping non-existing session")};
g.h.requestSession=function(){window.chrome.cast.requestSession((0,g.A)(this.Dw,this),(0,g.A)(this.PJ,this))};
g.h.U=function(){this.l.unsubscribe("onlineScreenChange",(0,g.A)(this.Vy,this));window.chrome&&window.chrome.cast&&window.chrome.cast.removeReceiverActionListener(this.A);g.Za(g.z("yt.mdx.remote.debug.handlers_")||[],k6);g.ff(this.g);T6.wa.U.call(this)};
g.h.zb=function(a){o6("Controller",a)};
g.h.Ew=function(a,b){this.g==a&&(b||X6(this,null),this.P("yt-remote-cast2-session-change",b))};
g.h.qJ=function(a,b){if(!this.ha())if(a)switch(a.friendlyName=window.chrome.cast.unescape(a.friendlyName),V6("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case window.chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.l.label!=a.label)V6("onReceiverAction_: Stopping active receiver: "+this.g.l.friendlyName),this.g.stop();else{V6("onReceiverAction_: Casting to active receiver.");this.g.o&&this.P("yt-remote-cast2-session-change",this.g.o);break}switch(a.receiverType){case window.chrome.cast.ReceiverType.CUSTOM:X6(this,
new S6(this.l,a));break;case window.chrome.cast.ReceiverType.DIAL:X6(this,new P6(this.l,a,this.C));break;case window.chrome.cast.ReceiverType.CAST:X6(this,new O6(this.l,a));break;default:this.zb("Unknown receiver type: "+a.receiverType)}break;case window.chrome.cast.ReceiverAction.STOP:this.g&&this.g.l.label==a.label?this.g.stop():this.zb("Stopping receiver w/o session: "+a.friendlyName)}else this.zb("onReceiverAction_ called without receiver.")};
g.h.CH=function(a){if(this.ha())return window.Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=window.chrome.cast.ReceiverType.DIAL&&(this.zb("Not DIAL receiver: "+b.friendlyName),b.receiverType=window.chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.l:null;if(!c||c.label!=b.label)return this.zb("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),window.Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=window.chrome.cast.ReceiverType.DIAL){if(this.g.o)return V6("Reselecting dial screen."),
this.P("yt-remote-cast2-session-change",this.g.o),window.Promise.resolve(new window.chrome.cast.DialLaunchResponse(!1));this.zb('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);X6(this,new P6(this.l,b,this.C))}b=this.g;b.G=a;return b.G.appState==window.chrome.cast.DialAppState.RUNNING?new window.Promise((0,g.A)(b.TB,b,(b.G.extraData||{}).screenId||null)):new window.Promise((0,g.A)(b.ho,b))};
g.h.Dw=function(a){if(!this.ha()){V6("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=window.chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==window.chrome.cast.ReceiverType.CAST)V6("Got resumed cast session before resumed mdx connection."),b.friendlyName=window.chrome.cast.unescape(b.friendlyName),X6(this,new O6(this.l,b),!0);else{this.zb("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.l,d=N4(this.l.pd(),c.label);
d&&G4(d,b.label)&&c.receiverType!=window.chrome.cast.ReceiverType.CAST&&b.receiverType==window.chrome.cast.ReceiverType.CAST&&(V6("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.ff(this.g),this.g=new O6(this.l,b),this.g.subscribe("sessionScreen",(0,g.A)(this.Ew,this,this.g)),this.g.Dh(null));this.g.bq(a)}}};
g.h.gM=function(){return this.g?this.g.Wy():null};
g.h.PJ=function(a){this.ha()||(this.zb("Failed to estabilish a session: "+g.Og(a)),a.code!=window.chrome.cast.ErrorCode.CANCEL&&X6(this,null))};
g.h.uJ=function(a){V6("Receiver availability updated: "+a);if(!this.ha()){var b=W6(this);this.B=a==window.chrome.cast.ReceiverAvailability.AVAILABLE;W6(this)!=b&&this.P("yt-remote-cast2-availability-change",W6(this))}};
g.h.Vy=function(){this.ha()||(this.o=Y6(this),V6("Updating custom receivers: "+g.Og(this.o)),window.chrome.cast.setCustomReceivers(this.o,g.za,(0,g.A)(function(){this.zb("Failed to set custom receivers.")},this)),this.P("yt-remote-cast2-availability-change",W6(this)))};
T6.prototype.setLaunchParams=T6.prototype.oL;T6.prototype.setConnectedScreenStatus=T6.prototype.nL;T6.prototype.stopSession=T6.prototype.hM;T6.prototype.getCastSession=T6.prototype.gM;T6.prototype.requestSession=T6.prototype.requestSession;T6.prototype.init=T6.prototype.init;T6.prototype.dispose=T6.prototype.dispose;var g7=[];o7.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";p7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.g=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.l=a.trackData,this.ze=a.hasPrevious,this.hasNext=a.hasNext,this.G=a.playerTime,this.D=a.playerTimeAt,this.B=a.seekableStart,this.o=a.seekableEnd,this.I=a.duration,this.J=a.loadedTime,this.A=a.liveIngestionTime,this.C=!(0,window.isNaN)(this.A))};
o7.prototype.isAdPlaying=function(){return 1081==this.g};
o7.prototype.clone=function(){return new o7(u7(this))};g.B(x7,g.O);g.h=x7.prototype;g.h.play=function(){1==this.g?(this.l?this.l.play(null,g.za,F7(this,"play")):D7(this,"play"),C7(this,1,s7(y7(this))),this.P("remotePlayerChange")):A7(this,this.play)};
g.h.pause=function(){1==this.g?(this.l?this.l.pause(null,g.za,F7(this,"pause")):D7(this,"pause"),C7(this,2,s7(y7(this))),this.P("remotePlayerChange")):A7(this,this.pause)};
g.h.Ry=function(a){if(1==this.g){if(this.l){var b=y7(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=1==b.g||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.l.seek(c,g.za,F7(this,"seekTo",{newTime:a}))}else D7(this,"seekTo",{newTime:a});C7(this,3,a);this.P("remotePlayerChange")}else A7(this,g.La(this.Ry,a))};
g.h.stop=function(){if(1==this.g){this.l?this.l.stop(null,g.za,F7(this,"stopVideo")):D7(this,"stopVideo");var a=y7(this);a.index=-1;a.videoId="";p7(a);B7(this,a);this.P("remotePlayerChange")}else A7(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=y7(this);if(this.o){if(c.volume!=a){var d=Math.round(a)/100;this.o.setReceiverVolumeLevel(d,(0,g.A)(function(){o6("CP","set receiver volume: "+d)},this),(0,g.A)(function(){this.zb("failed to set receiver volume.")},this))}c.muted!=b&&this.o.setReceiverMuted(b,(0,g.A)(function(){o6("CP","set receiver muted: "+b)},this),(0,g.A)(function(){this.zb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);D7(this,"setVolume",e)}c.muted=b;c.volume=a;B7(this,c)}else A7(this,g.La(this.setVolume,a,b))};
g.h.Px=function(a,b){if(1==this.g){var c=y7(this),d={videoId:a};b&&(c.l={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.Og(b.style),g.tc(d,c.l));D7(this,"setSubtitlesTrack",d);B7(this,c)}else A7(this,g.La(this.Px,a,b))};
g.h.Dq=function(a,b){if(1==this.g){D7(this,"setAudioTrack",{videoId:a,audioTrackId:b.ab.id});var c=y7(this);c.audioTrackId=b.ab.id;B7(this,c)}else A7(this,g.La(this.Dq,a,b))};
g.h.Qy=function(a,b){if(1==this.g){if(a&&b){var c=y7(this);t7(c,a,b);B7(this,c)}D7(this,"previous")}else A7(this,g.La(this.Qy,a,b))};
g.h.Py=function(a,b){if(1==this.g){if(a&&b){var c=y7(this);t7(c,a,b);B7(this,c)}D7(this,"next")}else A7(this,g.La(this.Py,a,b))};
g.h.rs=function(){1==this.g?D7(this,"dismissAutoplay"):A7(this,this.rs)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.P("proxyStateChange",a,this.g)}x7.wa.dispose.call(this)};
g.h.U=function(){z7(this);this.A=null;this.B.clear();w7(this,null);x7.wa.U.call(this)};
g.h.Eq=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.P("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)b=a=this.B,0==b.g.length&&(b.g=b.l,b.g.reverse(),b.l=[]),a.g.pop().apply(this);else 3==a&&this.dispose()}};
g.h.mJ=function(a,b){this.P(a,b)};
g.h.hH=function(a){if(!a)this.tj(null),w7(this,null);else if(this.o.receiver.volume){a=this.o.receiver.volume;var b=y7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)o6("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,B7(this,b)}};
g.h.tj=function(a){o6("CP","Cast media: "+!!a);this.l&&this.l.removeUpdateListener(this.G);if(this.l=a)this.l.addUpdateListener(this.G),E7(this),this.P("remotePlayerChange")};
g.h.gH=function(a){a?(E7(this),this.P("remotePlayerChange")):this.tj(null)};
g.h.tH=function(){var a=k7();a&&w7(this,a)};
g.h.zb=function(a){o6("CP",a)};g.B(G7,g.O);g.h=G7.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.t(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.t(k)&&(l.currentIndex=k);c&&(this.La.listId=c);this.La.videoId=d;this.La.index=k||0;this.La.state=3;r7(this.La,m);this.A="UNSUPPORTED";H7("Connecting with setPlaylist and params: "+g.Og(l));this.g.connect({method:"setPlaylist",params:g.Og(l)},
a,T4())}else H7("Connecting without params"),this.g.connect({},a,T4());yla(this)};
g.h.dispose=function(){this.ha()||(this.P("beforeDispose"),I7(this,3));G7.wa.dispose.call(this)};
g.h.U=function(){J7(this);L7(this);K7(this);g.Mr(this.I);this.I=window.NaN;g.Mr(this.J);this.J=window.NaN;this.o=null;g.bt(this.T);this.T.length=0;this.g.dispose();G7.wa.U.call(this);this.A=this.D=this.l=this.La=this.g=null};
g.h.eB=function(){this.C(2)};
g.h.lH=function(){H7("Channel opened");this.R&&(this.R=!1,K7(this),this.O=g.Kr((0,g.A)(function(){H7("Timing out waiting for a screen.");this.C(1)},this),15E3));
Vka(gla(this.g),this.Y)};
g.h.iH=function(){H7("Channel closed");(0,window.isNaN)(this.B)?W4(!0):W4();this.dispose()};
g.h.jH=function(a){W4();(0,window.isNaN)(this.G())?(H7("Channel error: "+a+" without reconnection"),this.dispose()):(this.R=!0,H7("Channel error: "+a+" with reconnection in "+this.G()+" ms"),I7(this,2))};
g.h.kH=function(a){a.params?H7("Received: action="+a.action+", params="+g.Og(a.params)):H7("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.Fq(a.params.devices);this.l=(0,g.E)(a,function(a){return new E4(a)});
a=!!g.Ra(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
O7(this,a);break;case "loungeScreenDisconnected":g.ab(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
O7(this,!1);break;case "remoteConnected":var b=new E4(g.Fq(a.params.device));g.Ra(this.l,function(a){return b?a.id==b.id:!1})||g.Xa(this.l,b);
break;case "remoteDisconnected":b=new E4(g.Fq(a.params.device));g.ab(this.l,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":P7(this,a);break;case "nowPlaying":Bla(this,a);break;case "onStateChange":Q7(this,a);break;case "onAdStateChange":Cla(this,a);break;case "onVolumeChanged":Dla(this,a);break;case "onSubtitlesTrackChanged":Ala(this,a);break;case "nowAutoplaying":Ela(this,a);break;case "autoplayDismissed":this.P("autoplayDismissed");break;case "autoplayUpNext":this.D=a.params.videoId||null;this.P("autoplayUpNext",this.D);break;case "onAutoplayModeChanged":this.A=
a.params.autoplayMode;this.P("autoplayModeChange",this.A);"DISABLED"==this.A&&this.P("autoplayDismissed");break;case "onHasPreviousNextChanged":Fla(this,a);break;case "requestAssistedSignIn":this.P("assistedSignInRequested",a.params.authCode);break;default:H7("Unrecognized action: "+a.action)}};
g.h.bL=function(){if(this.o){var a=this.o;this.o=null;this.La.videoId!=a&&M7(this,"getNowPlaying")}};
G7.prototype.subscribe=G7.prototype.subscribe;G7.prototype.unsubscribeByKey=G7.prototype.Bc;G7.prototype.ea=function(){var a=3;this.ha()||(a=0,(0,window.isNaN)(this.G())?g6(this.g)&&(0,window.isNaN)(this.B)&&(a=1):a=2);return a};
G7.prototype.getProxyState=G7.prototype.ea;G7.prototype.C=function(a){H7("Disconnecting with "+a);J7(this);this.P("beforeDisconnect",a);1==a&&W4();f6(this.g,a);this.dispose()};
G7.prototype.disconnect=G7.prototype.C;G7.prototype.ca=function(){var a=this.La;this.o&&(a=this.La.clone(),t7(a,this.o,a.index));return u7(a)};
G7.prototype.getPlayerContextData=G7.prototype.ca;
G7.prototype.na=function(a){var b=new o7(a);b.videoId&&b.videoId!=this.La.videoId&&(this.o=b.videoId,g.Mr(this.I),this.I=g.Kr((0,g.A)(this.bL,this),5E3));var c=[];this.La.listId==b.listId&&this.La.videoId==b.videoId&&this.La.index==b.index||c.push("remoteQueueChange");this.La.g==b.g&&this.La.volume==b.volume&&this.La.muted==b.muted&&s7(this.La)==s7(b)&&g.Og(this.La.l)==g.Og(b.l)||c.push("remotePlayerChange");this.La.reset(a);(0,g.C)(c,function(a){this.P(a)},this)};
G7.prototype.setPlayerContextData=G7.prototype.na;G7.prototype.Z=function(){var a=this.g.C.id,b=g.Ra(this.l,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
G7.prototype.getOtherConnectedRemoteId=G7.prototype.Z;G7.prototype.G=function(){var a=this.g;return a.l.isActive()?a.l.l-(0,g.D)():window.NaN};
G7.prototype.getReconnectTimeout=G7.prototype.G;G7.prototype.X=function(){return this.A||"UNSUPPORTED"};
G7.prototype.getAutoplayMode=G7.prototype.X;G7.prototype.fa=function(){return this.D||""};
G7.prototype.getAutoplayVideoId=G7.prototype.fa;G7.prototype.va=function(){if(!(0,window.isNaN)(this.G())){var a=this.g.l;g.vq(a.g);a.start()}};
G7.prototype.reconnect=G7.prototype.va;G7.prototype.la=function(a,b){M7(this,a,b);N7(this)};
G7.prototype.sendMessage=G7.prototype.la;g.B(R7,s6);g.h=R7.prototype;g.h.pd=function(a){return this.zc.$_gs(a)};
g.h.contains=function(a){return!!this.zc.$_c(a)};
g.h.get=function(a){return this.zc.$_g(a)};
g.h.start=function(){this.zc.$_st()};
g.h.add=function(a,b,c){this.zc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.zc.$_r(a,b,c)};
g.h.Bm=function(a,b,c,d){this.zc.$_un(a,b,c,d)};
g.h.U=function(){for(var a=0,b=this.l.length;a<b;++a)this.zc.$_ubk(this.l[a]);this.l.length=0;this.zc=null;R7.wa.U.call(this)};
g.h.dM=function(){this.P("screenChange")};
g.h.SI=function(){this.P("onlineScreenChange")};
F6.prototype.$_st=F6.prototype.start;F6.prototype.$_gspc=F6.prototype.eM;F6.prototype.$_gsppc=F6.prototype.Uy;F6.prototype.$_c=F6.prototype.contains;F6.prototype.$_g=F6.prototype.get;F6.prototype.$_a=F6.prototype.add;F6.prototype.$_un=F6.prototype.Bm;F6.prototype.$_r=F6.prototype.remove;F6.prototype.$_gs=F6.prototype.pd;F6.prototype.$_gos=F6.prototype.Ty;F6.prototype.$_s=F6.prototype.subscribe;F6.prototype.$_ubk=F6.prototype.Bc;var S7=null,T7=null,i8=null,X7=[];g.r(l8,g.G);g.h=l8.prototype;
g.h.U=function(){g.G.prototype.U.call(this);this.A.stop();this.B.stop();this.M.stop();this.R();this.g.unsubscribe("proxyStateChange",this.Aw,this);this.g.unsubscribe("remotePlayerChange",this.uj,this);this.g.unsubscribe("remoteQueueChange",this.Nl,this);this.g.unsubscribe("autoplayUpNext",this.aw,this);this.g.unsubscribe("previousNextChange",this.xw,this);this.g.unsubscribe("nowAutoplaying",this.rw,this);this.g.unsubscribe("autoplayDismissed",this.Zv,this);this.g=this.G=null};
g.h.Vu=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(p8(this)){if(!y7(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":1==y7(this.g).g?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.J.th(c[0],c[1]);break;case "control_subtitles_set_track":q8(this,c[0]);break;case "control_set_audio_track":c=c[0],p8(this)&&this.g.Dq(this.l.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.l.getCurrentTime();r8(this,0==c?void 0:c);break;case "control_seek":r8(this,c[0]);break;case "control_subtitles_set_track":q8(this,c[0]);break;case "control_set_audio_track":c=c[0],p8(this)&&this.g.Dq(this.l.getVideoData(1).videoId,c)}};
g.h.fH=function(a){this.M.ZA(a)};
g.h.KL=function(a){this.Vu("control_subtitles_set_track",g.lc(a)?null:a)};
g.h.fy=function(){var a=this.l.Nb("captions","track");g.lc(a)||q8(this,a)};
g.h.pw=function(a){if(p8(this)){this.g.unsubscribe("remotePlayerChange",this.uj,this);var b=Math.round(a.volume);a=!!a.muted;var c=y7(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.O.start();this.g.subscribe("remotePlayerChange",this.uj,this)}};
g.h.iI=function(){g.lc(this.C)||s8(this,this.C);this.D=!1};
g.h.Aw=function(a,b){this.B.stop();2==b&&this.by()};
g.h.uj=function(){if(p8(this)){this.A.stop();var a=y7(this.g);switch(a.g){case 1081:case 1:n8(this,new g.hD(8));this.ay();break;case 1085:case 3:n8(this,new g.hD(9));break;case 1083:case 0:n8(this,new g.hD(2));this.J.stop();m8(this,this.l.getVideoData().lengthSeconds);break;case 1084:n8(this,new g.hD(4));break;case 2:n8(this,new g.hD(4));m8(this,s7(a));break;case -1:n8(this,new g.hD(64));break;case -1E3:n8(this,new g.hD(128,{errorCode:"mdx.remoteerror",message:"This video is not available for remote playback."}))}a=
y7(this.g).l;var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.C=a,s8(this,a));a=y7(this.g);-1==a.volume||Math.round(this.l.Bb())==a.volume&&this.l.isMuted()==a.muted||this.O.isActive()||this.Fy()}else o8(this)};
g.h.xw=function(){this.l.P("mdxpreviousnextchange")};
g.h.Nl=function(){p8(this)||o8(this)};
g.h.vA=function(){this.g.rs()};
g.h.aw=function(a){a&&(a=g.as("/watch_queue_ajax",{method:"GET",xc:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.A)(this.oK,this)}))&&(this.R=(0,g.A)(a.abort,a))};
g.h.oK=function(a,b){var c=new g.$B({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.l.P("mdxautoplayupnext",c)};
g.h.rw=function(a){(0,window.isNaN)(a)||this.l.P("mdxnowautoplaying",a)};
g.h.Zv=function(){this.l.P("mdxautoplaycanceled")};
g.h.TE=function(a,b){-1==y7(this.g).g?r8(this,a):b&&this.g.Ry(a)};
g.h.Fy=function(){if(p8(this)){var a=y7(this.g);this.o.Ja(this.T);a.muted?this.l.mute():this.l.Ee();this.l.setVolume(a.volume);this.T=this.o.L(this.l,"onVolumeChange",this.pw)}};
g.h.ay=function(){this.A.stop();if(!this.g.ha()){var a=y7(this.g);1==a.g&&n8(this,new g.hD(8));m8(this,s7(a));this.A.start()}};
g.h.by=function(){this.B.stop();this.A.stop();var a=this.g.A.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.B.start()};g.r(v8,g.R);v8.prototype.A=function(a){u8(this,a.state)};g.r(w8,g.CT);w8.prototype.J=function(){var a=this.l.Nb("remote","receivers");a&&1<a.length&&!this.l.Nb("remote","quickCast")?(this.G=g.ub(a,this.B,this),g.DT(this,(0,g.E)(a,this.B)),a=this.l.Nb("remote","currentReceiver"),this.ce(this.B(a)),this.enable(!0)):this.enable(!1)};
w8.prototype.B=function(a){return a.key};
w8.prototype.be=function(a){return"cast-selector-receiver"==a?"Cast...":this.G[a].name};
w8.prototype.Ic=function(a){g.CT.prototype.Ic.call(this,a);this.l.Xc("remote","currentReceiver",this.G[a]);this.A.ob()};g.r(x8,g.zK);g.h=x8.prototype;g.h.create=function(){Kla(g.dA(g.V(this.g)));this.C.push(g.Dt("yt-remote-before-disconnect",this.cH,this));this.C.push(g.Dt("yt-remote-connection-change",this.vJ,this));this.C.push(g.Dt("yt-remote-receiver-availability-change",this.yw,this));this.C.push(g.Dt("yt-remote-auto-connect",this.tJ,this));this.C.push(g.Dt("yt-remote-receiver-resumed",this.sJ,this));this.yw()};
g.h.load=function(){this.g.Yo();g.zK.prototype.load.call(this);this.B=new l8(this,this.g,this.l);var a=(a=k8())?a.currentTime:0;var b=h8()?new x7(c8(),void 0):null;0==a&&b&&(a=s7(y7(b)));0!=a&&(this.I=a||0,this.g.P("progresssync",a,void 0));t8(this,this.D,this.D);g.GV(this.g.app,6)};
g.h.unload=function(){this.g.P("mdxautoplaycanceled");this.A=this.o;g.gf(this.B,this.l);this.l=this.B=null;g.zK.prototype.unload.call(this);g.GV(this.g.app,5)};
g.h.U=function(){g.Et(this.C);g.zK.prototype.U.call(this)};
g.h.mj=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.B.Vu.apply(this.B,[a].concat(g.oa(c)))};
g.h.WA=function(){return this.loaded?this.B.suggestion:null};
g.h.ze=function(){return this.l?y7(this.l).ze:!1};
g.h.hasNext=function(){return this.l?y7(this.l).hasNext:!1};
g.h.getCurrentTime=function(){return this.I};
g.h.JE=function(){var a=y7(this.l),b=this.g.getVideoData();return{allowSeeking:this.g.Ac(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.C?a.I+q7(a):a.I,ingestionTime:a.C?a.A+q7(a):a.A,isPeggedToLive:1>=(a.C?a.o+q7(a):a.o)-this.getCurrentTime(),loaded:a.J,seekableEnd:a.C?a.o+q7(a):a.o,seekableStart:0<a.B?a.B+q7(a):a.B}};
g.h.KE=function(){this.l&&this.l.Py()};
g.h.LE=function(){this.l&&this.l.Qy()};
g.h.cH=function(a){1==a&&(this.J=this.l?y7(this.l):null)};
g.h.vJ=function(){var a=h8()?new x7(c8(),void 0):null;if(a){var b=this.A;this.loaded&&this.unload();this.l=a;this.J=null;b.key!=this.o.key&&(this.A=b,this.load())}else g.ff(this.l),this.l=null,this.loaded&&(this.unload(),(a=this.J)&&a.videoId==this.g.getVideoData().videoId&&this.g.Au(a.videoId,s7(a)));this.g.P("videodatachange","newdata",this.g.getVideoData(),3)};
g.h.yw=function(){this.G=[this.o].concat(Lla());var a=d8()||this.o;y8(this,a);this.g.ma("onMdxReceiversChange")};
g.h.tJ=function(){var a=d8();y8(this,a)};
g.h.sJ=function(){this.A=d8()};
g.h.IE=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.G;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?m7():y8(this,b)),this.loaded?this.A:this.o;case "quickCast":return 2==this.G.length&&"cast-selector-receiver"==this.G[1].key?(b&&m7(),!0):!1}};
g.h.ME=function(){D7(this.l,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Xb=function(){return!1};g.HQ.remote=x8;})(_yt_player);
